alphagov/pay-direct-debit-connector

Jenkinsfile
- Based on `pay-connector`:
- Maven build: `mvn clean package`
- Docker tag `direct-debit-connector`
=> PP-2808 Pay Direct Debit connector Jenkinsfile

Jenkinsfile
- Must be equal to [Dockerhub](https://hub.docker.com/r/govukpay/directdebit-connector/) repository name.
=> PP-2808 Fix App name

Jenkinsfile
- This adds the deploy step to deploy to the ECS cluster. 
- Deploying to the ECS cluster currently not working, this is just the placeholder for when that work is done, currently in progress.
=> PP-2808 Deploying to the ECS cluster

README.md
- Add env vars in README.md file
=> PP-2808 Add env vars in README

Jenkinsfile, README.md
=> PP-2808 Add wiki link to README.md

pom.xml, src/test/java/uk/gov/pay/directdebit/app/healthchecks/PingTest.java
- Added `dependencyManagement` for Dropwizard
- Upgraded Dropwizard to latest stable version (`1.2.0`) and upgraded all other libraries
=> PP-2808 Upgrade Dropwizard and other libraries

Dockerfile, chamber.sha256sum, docker-startup.sh, update-chamber.sh
This PR adds [Chamber](https://github.com/segmentio/chamber) integration as part of Docker image.
Based on following PR: https://github.com/alphagov/pay-selfservice/pull/551
Please see commits for more information.
=> PP-2905 Added Chamber to support AWS EC2 parameter store

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
=> PP-2971 Add Proxy config to dd connector app

pom.xml, src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java, src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitConfig.java, src/main/java/uk/gov/pay/directdebit/app/config/GraphiteConfig.java, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
Sending out dropwizard metrics in similar fashion to how's done in the other java apps. Metrics should be picked up by telegraf and sent to HG
=> PP-3117 Add dropwizard metrics

src/main/java/uk/gov/pay/directdebit/common/exception/validation/InvalidSizeFieldsException.java, src/main/java/uk/gov/pay/directdebit/common/validation/ApiValidation.java, src/main/java/uk/gov/pay/directdebit/common/validation/FieldSize.java, src/main/java/uk/gov/pay/directdebit/payers/api/CreatePayerValidator.java, src/main/java/uk/gov/pay/directdebit/payments/api/PaymentRequestValidator.java, src/test/java/uk/gov/pay/directdebit/payers/api/CreatePayerValidatorTest.java, src/test/java/uk/gov/pay/directdebit/payers/resources/PayerResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/api/PaymentRequestValidatorTest.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentRequestResourceIT.java
- Finished validation for `v1/api/accounts/{accountId}/charges` and (uk.gov.pay.directdebit.payments.resources.PaymentRequestResource.createNewPaymentRequest)[https://github.com/alphagov/pay-direct-debit-connector/blob/0334d002ef44775d67c69fc037ab0dba9efcab2c/src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentRequestResource.java#L48] endpoint and added tests
- Removed not-needed integration tests
=> PP-3080 "/v1/api/accounts/{accountId}/charges" endpoint validation

src/main/java/uk/gov/pay/directdebit/payments/api/PaymentRequestValidator.java
- Change max amount to `500000` pence which is `5000` pounds
- Small refactoring of the names
=> PP-3080 Change max amount validation

Dockerfile, run-with-chamber.sh
chamber is now in our base image
solo @tlwr
=> BAU: Use chamber from base image

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDao.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/dao/mapper/GatewayAccountMapper.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/exception/InvalidGatewayAccountTypeException.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/exception/InvalidPaymentProviderException.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/model/GatewayAccount.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/model/PaymentProvider.java, src/test/java/uk/gov/pay/directdebit/payments/dao/GatewayAccountDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/fixtures/GatewayAccountFixture.java, src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java
First PR for adding support of gateway accounts in dd connector.
- Adding DAO + mapper, fixtures and relative tests
- This will be followed by another PR where we add service and resource
Please not merge this right now, still waiting for migrations to run on dd connector.
=> PP-3061 Add gateway accounts dao

src/main/resources/migrations/00010_create_table_gocardless_mandates.sql, src/main/resources/migrations/00011_create_table_gocardless_payments.sql
- These tables will link our model to gocardless', without polluting our
own domain objects with concepts specific to gocardless' implementaiton of
direct debit
=> PP-2890 Add gocardless_mandates and gocardless_payments tables

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/api/GatewayAccountResponse.java, src/main/java/uk/gov/pay/directdebit/mandate/model/ConfirmationDetails.java, src/main/java/uk/gov/pay/directdebit/mandate/model/GoCardlessMandate.java, src/main/java/uk/gov/pay/directdebit/mandate/model/GoCardlessPayment.java, src/main/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResource.java, src/main/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmService.java, src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java, src/test/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
=> PP-2890 Use default equals and hashcode instead of guava's

docker-startup.sh
=> PP-3443 I can't type

src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java, src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
=> PP-3238 Fix order of logging calls

src/main/resources/config/config.yaml
=> PP-3360 Rename notify keys for consistency with the others in parameterstore

pom.xml, src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/config/GoCardlessFactory.java
Replace client with updated rc which has the proxy and ssl socket
factory modifications.
with @simad @belindac
=> PP-3541 Integrate GoCardlessClient v3.0.0

pom.xml, src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/config/GoCardlessFactory.java
This reverts commit 7684f867ee48f5a4020ca3cedb6e899d8eb391c1.
Smoke test is now failing
solo @belindac
=> Revert "PP-3541 Integrate GoCardlessClient v3.0.0"

pom.xml, src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/config/GoCardlessFactory.java
GoCardless has released a new version of their client which allows us to inject our ssl factory and use a proxy.
=> PP-3541 Update gocardless client and remove hackity hack

pom.xml, src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/config/GoCardlessFactory.java
Reverts alphagov/pay-direct-debit-connector#98
=> Revert "PP-3541 Update gocardless client and remove hackity hack"

pom.xml, src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/config/GoCardlessFactory.java
Reverts alphagov/pay-direct-debit-connector#100
=> Revert "Revert "PP-3541 Update gocardless client and remove hackity hack""

docker-startup.sh
Add `JAVA_OPTS` when running Java process
=> BAU: Add $JAVA_OPTS when running Java process

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountService.java, src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java, src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java, src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/directdebit/payments/model/Transaction.java, src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java, src/main/java/uk/gov/pay/directdebit/tokens/api/TokenResponse.java, src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountServiceTest.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResourceIT.java, src/test/java/uk/gov/pay/directdebit/payers/resources/PayerResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/fixtures/TransactionFixture.java, src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java, src/test/java/uk/gov/pay/directdebit/tokens/resources/SecurityTokensResourceIT.java
This PR exposes external gateway account id which will be needed to query `/v1/api/accounts/{accountId}` endpoint.
It also changes the JDBI queries to be explicit.
=> PP-3545 Use gateway account external id

src/test/java/uk/gov/pay/directdebit/mandate/dao/GoCardlessPaymentDaoIT.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResourceIT.java, src/test/java/uk/gov/pay/directdebit/payers/dao/GoCardlessCustomerDaoIT.java, src/test/java/uk/gov/pay/directdebit/payers/dao/PayerDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/dao/GoCardlessEventDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestEventDaoIT.java, src/test/java/uk/gov/pay/directdebit/tokens/dao/TokenDaoIT.java
- pre-fix relevant test for adding fk to payment_requests ref gateway_accounts (id)
=> PP-3646 Pre-fix tests for fk addition

env.sh
- change the env path in the env.sh file to match that of pay-scripts
=> PP-3646 Change env file path to match pay-scripts

src/main/resources/migrations/00016_alter_table_payment_requests_add_fk_gateway_accounts.sql
- add foreign key constraint to payment_requests referencing gateway_accounts id
=> PP-3646 Add fk to payment_requests

pom.xml
Upgrade Dropwizard and rest of the libraries
=> PP-3545 Upgrade Dropwizard and rest of the libraries

Dockerfile
Install curl for debugging purposes
=> Install curl for debugging purposes

pom.xml
Downgrade GoCardless client back to 3.0.0-rc1
=> Downgrade GoCardless client back to 3.0.0-rc1

Dockerfile, pom.xml
Upgrade GoCardless client back to `3.1.0` and remove `curl` installation from `Dockerfile`
=> Upgrade GoCardless client back to `3.1.0` and remove `curl`

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java
- Handle payment `FAILED` webhook action
=> PP-3362 Handle payment FAILED action

src/main/java/uk/gov/pay/directdebit/notifications/model/EmailPayload.java, src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java, src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessHandler.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java, src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceIT.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessMandateHandlerTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessHandlerTest.java
Added payment `FAILED` action email integration with `PAYMENT_FAILED` template
=> PP-3362 Payment FAILED action email integration

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/GatewayAccountParamConverterProvider.java, src/main/java/uk/gov/pay/directdebit/payers/model/Payer.java, src/main/java/uk/gov/pay/directdebit/payments/api/PaymentRequestFrontendResponse.java, src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentRequestResource.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestService.java, src/test/java/uk/gov/pay/directdebit/gatewayaccounts/GatewayAccountParamConverterProviderTest.java, src/test/java/uk/gov/pay/directdebit/payments/api/PaymentRequestFrontendResponseTest.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentRequestResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentRequestServiceTest.java, src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java
https://github.com/alphagov/pay-direct-debit-frontend/pull/75 expects to retrieve a payment request from a new endpoint, returning some additional information to what's returned from public api.
This PR adds the endpoint to direct debit connector.
=> PP-3701 Add endpoint to retrieve payment request from frontend

src/main/java/uk/gov/pay/directdebit/common/exception/validation/ValidationException.java, src/main/java/uk/gov/pay/directdebit/common/validation/BankAccountDetailsValidator.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/GatewayAccountParamConverterProvider.java, src/main/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResource.java, src/main/java/uk/gov/pay/directdebit/payers/api/BankAccountValidationResponse.java, src/main/java/uk/gov/pay/directdebit/payers/api/PayerParser.java, src/main/java/uk/gov/pay/directdebit/payers/dao/PayerDao.java, src/main/java/uk/gov/pay/directdebit/payers/dao/mapper/PayerMapper.java, src/main/java/uk/gov/pay/directdebit/payers/model/BankAccountDetails.java, src/main/java/uk/gov/pay/directdebit/payers/model/BankAccountDetailsParser.java, src/main/java/uk/gov/pay/directdebit/payers/model/GoCardlessBankAccountLookup.java, src/main/java/uk/gov/pay/directdebit/payers/model/Payer.java, src/main/java/uk/gov/pay/directdebit/payers/resources/PayerResource.java, src/main/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientFacade.java, src/main/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientWrapper.java, src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestDao.java, src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java, src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentRequestMapper.java, src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitPaymentProvider.java, src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java, src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java, src/test/java/uk/gov/pay/directdebit/mandate/api/BankAccountDetailsValidatorTest.java, src/test/java/uk/gov/pay/directdebit/payers/dao/PayerDaoIT.java, src/test/java/uk/gov/pay/directdebit/payers/fixtures/PayerFixture.java, src/test/java/uk/gov/pay/directdebit/payers/services/PayerServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientFacadeTest.java, src/test/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientWrapperTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java
The new endpoint will be called from frontend before submitting direct debit details. It should also be used in the future to do a more refined (eg. on-blur) validation.
=> PP-3714 Add bank account validation endpoint 

src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDao.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentViewService.java, src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDaoIT.java
Include in search results payment requests in status CREATED
=> Pp 3646 charge search

src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java, src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java, src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java, src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java, src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessMandateHandlerTest.java
- Had to refactor the code a bit because we switched payment reference to mandate reference.
Everything else is just about renaming a few variables.
=> PP-3713 Update direct debit email variables

src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResource.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceITest.java
=> PP-3646 Add search for payment requests

src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDao.java, src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java
=> BAU: small refactorings

Jenkinsfile
It does what it says (hopefully)
=> PP-3676 Fix option for not running e2e on PR build

Jenkinsfile
Silvia has wrought her hellish vision
=> Go back to using master branch of pay-jenkins library

Jenkinsfile, pom.xml, src/test/java/uk/gov/pay/directdebit/junit/DropwizardAppWithPostgresRule.java, src/test/java/uk/gov/pay/directdebit/pact/ContractTestSuite.java, src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
Provider test for interaction between publicapi and direct-debit-connector.
=> Publicapi contract test

Jenkinsfile, pom.xml, src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
Same as https://github.com/alphagov/pay-adminusers/blob/master/Jenkinsfile#L61
@oswaldquek
=> PP-3844: Run pact provider tests as part of build

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
=> PP-3677 Add mandate with external id fixture to pact

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
=> PP-3677 Make sure mandate has the right gateway account id for pact, for real

docs/api_specification.md
=> PP-3676 Added documentation for create agreement

src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java, src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
- We added default value placeholders for both Sandbox and GoCardless
with @georgeracu
=> PP-3676 Fix mandate reference generated when we use sandbox account

src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResponse.java, src/main/java/uk/gov/pay/directdebit/payments/links/PaginationLink.java, src/main/java/uk/gov/pay/directdebit/payments/model/ViewPaginationBuilder.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentViewService.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceITest.java
- add `PaginationLink` (to differ from `Link` format)
- refactor JsonProperties tags
- remove gateway_account_id from response (not needed)
- add relevant JsonIgnore to unwanted variables
- update relevant test
=> PP-3679 Refine search response json properties

src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResponse.java, src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResultResponse.java, src/main/java/uk/gov/pay/directdebit/payments/model/ViewPaginationBuilder.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentViewService.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentViewServiceTest.java
- rename PaymentViewListResponse to PaymentViewResultResponse
=> PP-3679 Rename PaymentViewListResponse to a more meaningful name

src/main/java/uk/gov/pay/directdebit/mandate/api/DirectDebitInfoFrontendResponse.java, src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java, src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
Add mandate type to response for frontend:
- Changed the response entity
- Updated tests
- Fixed spelling
with @danailminchev
=> PP-3671 Add mandate type to response for frontend

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java, src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java
The collect endpoint in publicapi is the same between card and dd payments, so we should return payment provider for consistency. 
=> PP-3678 Add payment provider to collect payment response

docs/api_specification.md, src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java
- add api documentation for Direct Debit search response
- small bugfix of query params url generator
=> PP3679 add api documentation

src/main/java/uk/gov/pay/directdebit/tokens/api/TokenResponse.java, src/test/java/uk/gov/pay/directdebit/tokens/resources/SecurityTokensResourceIT.java
=> PP-3671 Renamed type to mandate type in Token response

src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResultResponse.java, src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDao.java, src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentViewMapper.java, src/main/java/uk/gov/pay/directdebit/payments/model/PaymentView.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentViewService.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentViewServiceTest.java
- add mandate_external_id to select query
- add mandate_external_id to PaymentViewMapper
- refactor relevant uses
=> PP-3929 Add agreement id to transaction search results

src/main/java/uk/gov/pay/directdebit/notifications/model/EmailPayload.java, src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java, src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java, src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java, src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java, src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceOnDemandTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceOneOffTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java
- Updated MandateService to send email when creating mandate
- Updated UserNotificationService to send the mandate created template
=> PP-3676 Send email when creating mandate

src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java, src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java, src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
=> PP-3676 Added missing template keys for ON_DEMAND mandate created email

src/test/java/uk/gov/pay/directdebit/mandate/resources/ConfirmMandateSetupResourceIT.java
=> PP-3676 ConfirmMandateSetupResourceIT email tests

src/main/resources/migrations/00035_alter_table_events_add_external_id.sql
=> PP-3680: Add external id to events table

src/main/java/uk/gov/pay/directdebit/events/resources/DirectDebitEventsResource.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResource.java, src/main/java/uk/gov/pay/directdebit/healthcheck/resources/HealthCheckResource.java, src/main/java/uk/gov/pay/directdebit/mandate/resources/ConfirmMandateSetupResource.java, src/main/java/uk/gov/pay/directdebit/mandate/resources/MandateResource.java, src/main/java/uk/gov/pay/directdebit/payers/resources/PayerResource.java, src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResource.java, src/main/java/uk/gov/pay/directdebit/payments/resources/TransactionResource.java, src/main/java/uk/gov/pay/directdebit/tasks/resources/ExpireResource.java, src/main/java/uk/gov/pay/directdebit/tokens/resources/SecurityTokensResource.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResource.java, src/main/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResource.java
=> PP-4001 add timed annotation to all endpoints

src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountServiceTest.java
Testing that we call a method with `anyString` and any class is pointless, when we have all the information to test for specific things.
=> PP-3965 Actually test that we update access token and organisation with what we expect

Jenkinsfile
This reverts commit 84f65eb6dd826d0fdbdd72cdba79ed6b82683462.
=> Revert "BAU: publish test results in jenkins"

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java, src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
We are modifying the mandate reference, but the mandate embedded in transaction was not updated correctly for one-off mandates.
=> PP-4048 Make sure transaction has the updated mandate reference

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java, src/test/java/uk/gov/pay/directdebit/junit/DropwizardAppWithPostgresRule.java, src/test/java/uk/gov/pay/directdebit/junit/DropwizardConfig.java
- Upgrade PostgreSQL Docker image from `govukpay/postgres:9.4.4` to `govukpay/postgres:9.6.6`
=> BAU: Upgrade PostgreSQL Docker image

src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitConfig.java, src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java, src/main/java/uk/gov/pay/directdebit/app/config/GoCardlessAppConnectConfig.java, src/main/java/uk/gov/pay/directdebit/notifications/clients/ClientFactory.java, src/main/java/uk/gov/pay/directdebit/partnerapp/client/GoCardlessAppConnectClient.java, src/main/resources/config/config.yaml
- Added a new method to create a Jersey client with Proxy URI
- Updated checks if the response is valid
=> PP-4043 Add Proxy to web client

pom.xml
We just need the JPA functionality of EclipseLink and we already have a dependency for that
=> Remove dependency on full EclipseLink artifact

Jenkinsfile, pom.xml, src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
=> bau: upgrade pact lib

docker-startup.sh
We will pass these settings in via JAVA_OPTS instead.
=> PP-4584: Remove env vars for configuring HTTP proxies

Jenkinsfile, src/main/java/uk/gov/pay/directdebit/app/healthcheck/Database.java, src/main/java/uk/gov/pay/directdebit/events/api/DirectDebitEventsPagination.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/api/PatchGatewayAccountValidator.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountService.java, src/main/java/uk/gov/pay/directdebit/payments/dao/DirectDebitEventDao.java, src/test/java/uk/gov/pay/directdebit/events/resources/GetDirectDebitEventsTest.java, src/test/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDaoIT.java, src/test/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResourceIT.java, src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountServiceTest.java, src/test/java/uk/gov/pay/directdebit/partnerapp/resources/GoCardlessAppConnectAccountStateResourceTest.java, src/test/java/uk/gov/pay/directdebit/payers/model/AccountNumberTest.java, src/test/java/uk/gov/pay/directdebit/payers/model/SortCodeTest.java
- Simplify some tests
- Use try-with-resources for managing JDBC `Connection` objects
- Be more expressive / concise with our lambdas
- Small Jenkinsfile cleanup
- Remove unnecessary boxing
=> IntelliJ-inspired cleanups

src/main/java/uk/gov/pay/directdebit/app/healthcheck/Ping.java, src/main/java/uk/gov/pay/directdebit/app/ssl/TrustStoreLoader.java, src/main/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountService.java, src/main/java/uk/gov/pay/directdebit/healthcheck/resources/HealthCheckResource.java, src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java, src/main/java/uk/gov/pay/directdebit/payments/api/TransactionResponse.java, src/main/java/uk/gov/pay/directdebit/payments/dao/DirectDebitEventDao.java, src/main/java/uk/gov/pay/directdebit/payments/model/ViewPaginationBuilder.java, src/main/java/uk/gov/pay/directdebit/tasks/services/ExpireService.java, src/test/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDaoIT.java, src/test/java/uk/gov/pay/directdebit/tasks/resources/ExpireResourceTest.java
I ran IntelliJ's code analyser and picked the simplest most obvious things
=> Miscellaneous code cleanups

src/main/java/uk/gov/pay/directdebit/healthcheck/resources/HealthCheckResource.java
We can make HealthCheckResource cleaner by adopting a functional style with
streams.
=> Be more functional in HealthCheckResource

README.md, src/main/resources/config/config.yaml
Update README.md to describe all the environment variables used by
directdebit-connector and any default values they have.
*Note* I haven't described what the gocardless environment variables are for because I don't know
=> PP-5098: Document usage of environment variables

src/main/java/uk/gov/pay/directdebit/payments/dao/GoCardlessEventDao.java, src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/GoCardlessEventMapper.java, src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessEvent.java, src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessEventId.java, src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessEventIdArgumentFactory.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParser.java, src/test/java/uk/gov/pay/directdebit/junit/TestContext.java, src/test/java/uk/gov/pay/directdebit/payments/dao/GoCardlessDirectDebitDirectDebitEventDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/fixtures/GoCardlessEventFixture.java
`GoCardlessEventId` represents the ID GoCardless assign to one of their events. It wraps a string like `"EV123"`.
=> PP-5231 Introduce GoCardlessEventId type

src/main/resources/migrations/00047_alter_table_gocardless_events.sql
Add new columns to gocardless_event
=> PP-5244 Add migration to support storing of information from GoCardless in Database

src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java
This is a precursor to getting https://github.com/alphagov/pay-direct-debit-connector/pull/469 merged.
=> PP-5243: Remove mandate type from query

src/main/java/uk/gov/pay/directdebit/mandate/dao/GoCardlessPaymentDao.java, src/main/java/uk/gov/pay/directdebit/payments/dao/GoCardlessEventDao.java, src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/GoCardlessEventMapper.java, src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessEvent.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParser.java, src/test/java/uk/gov/pay/directdebit/payments/dao/GoCardlessDirectDebitDirectDebitEventDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/fixtures/GoCardlessEventFixture.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessEventServiceTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParserTest.java
Now stores all information from GoCardless events in the database with migrations to add columns to achieve this functionality.
=> PP-5244 Extract all information from GoCardlessEvent

src/main/resources/migrations/00050_create_table_sandbox_events.sql
Add new table to store SandboxEvents in the database.
=> PP-5244 Sandbox Events Storage

src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
Previously we were treating any exception thrown by the GoCardless bank account lookup as validation failed. However, we should only treat a 422 response, which the GoCardless SDK wraps into a ValidationFailedException as a validation failure.
If there is any other exception thrown by the SDK we now return a 500 response from our endpoint to validate bank details.
=> PP-5269 Handle GoCardless bank account lookup return correctly

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/api/GatewayAccountResponse.java, src/test/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResourceIT.java, src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountServiceTest.java
At this moment in time when we say linked, it's whether it's linked
specifically to a GoCardless account.
A bit tangential to the purpose of the PR but some test code cleanup in this PR
too.
=> PP-5266: Add flag to indicate whether account is linked

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java, src/test/java/uk/gov/pay/directdebit/pact/SelfServiceApiContractTest.java
I am writing a pact between selfservice and direct-debit to get a gateway account at the moment; this PR is the provider code to set up the state.
=> PP-5266: Set up state for getting a direct debit gateway account

src/main/resources/migrations/00056_alter_table_events_drop_fk_transactionId.sql
- Removing this as we transition from transactions table to payments table.
=> PP-5248 Drop events_transactions_fk constraint

src/main/resources/migrations/00057_alter_table_gocardless_payments_drop_contraint.sql
- Whilst we transition between transactions to payments.
=> PP-5428 Remove constraint between gocardless_payments and transactions

src/main/resources/migrations/00058_alter_table_payments_change_charge_date_type.sql
Alter table payment to change type of charge_date from timestamp with timezone to
date.
=> PP-5428 alter payment table to change type of charge_date

src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentDao.java, src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentMapper.java, src/main/java/uk/gov/pay/directdebit/payments/model/Payment.java, src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/fixtures/PaymentFixture.java
=> PP-5428 Add chargeDate to Payment

src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/MandateMapper.java
When reading a `Mandate` from the database, examine the payment provider to determine whether to instantiate a `SandboxMandateId` or a `GoCardessMandateId` rather than always using the latter.
=> PP-5248 Instantiate correct PaymentProviderMandateId type

src/main/java/uk/gov/pay/directdebit/events/dao/SandboxEventDao.java, src/main/java/uk/gov/pay/directdebit/events/model/SandboxEvent.java, src/main/java/uk/gov/pay/directdebit/payments/model/SandboxPaymentIdArgumentFactory.java, src/main/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResource.java, src/test/java/uk/gov/pay/directdebit/events/dao/SandboxEventDaoIT.java, src/test/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResourceIT.java
=> PP-5248 Use SandboxPaymentId type within SandboxEvent

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequestValidator.java, src/test/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequestValidatorTest.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
Allow for the description field on a collect payment request to be null
=> PP-5298 Allow description on collect payment to be null

src/main/resources/migrations/00059_drop_table_transactions.sql
=> PP-5248 Drop the transactions table, which is no longer used

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
This fixes https://github.com/alphagov/pay-publicapi/pull/549/
=> PP-5299: Provider state for adding a specific mandate reference

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
=> bau: Revert tags

src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java, src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
These should be null on mandate creation, when the payment provider is
GoCardless.
Also removed
MandateResourceIT.confirm_shouldCreateAMandateWithoutPayment_ifMandateIsOnDemand
as it's covered by confirm_shouldCreateACustomerBankAccountMandate.
=> PP-5299: Provider id and mandate reference should be null

src/main/java/uk/gov/pay/directdebit/mandate/api/GetMandateResponse.java, src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/MandateMapper.java, src/main/java/uk/gov/pay/directdebit/mandate/model/Mandate.java, src/main/java/uk/gov/pay/directdebit/mandate/model/MandateStatesGraph.java, src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java, src/test/java/uk/gov/pay/directdebit/util/GoCardlessStubs.java, src/test/resources/it/responses/gocardless/create-mandate-success.json
This should fix https://github.com/alphagov/pay-publicapi/pull/553
=> PP-5299: Return provider id and mandate ref on mandate confirmation

src/main/java/uk/gov/pay/directdebit/mandate/api/DirectDebitInfoFrontendResponse.java, src/main/java/uk/gov/pay/directdebit/mandate/api/MandateResponse.java, src/main/java/uk/gov/pay/directdebit/mandate/model/Mandate.java, src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java, src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java, src/main/java/uk/gov/pay/directdebit/tokens/api/TokenResponse.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java, src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
=> PP-5299: The mandate bank statement reference is optional

src/main/java/uk/gov/pay/directdebit/mandate/api/DirectDebitInfoFrontendResponse.java, src/main/java/uk/gov/pay/directdebit/mandate/api/MandateResponse.java, src/main/java/uk/gov/pay/directdebit/mandate/api/Payer.java, src/main/java/uk/gov/pay/directdebit/mandate/model/Mandate.java, src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java, src/main/java/uk/gov/pay/directdebit/notifications/clients/AdminUsersClient.java, src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java, src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
=> PP-5299: Return payer name and email when getting mandate

src/main/java/uk/gov/pay/directdebit/mandate/api/MandateResponse.java, src/main/java/uk/gov/pay/directdebit/mandate/resources/MandateResource.java, src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java, src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java, src/test/java/uk/gov/pay/directdebit/util/ResponseDoesNotContainLinkMatcher.java
Do not merge until https://github.com/alphagov/pay-publicapi/pull/567 has been deployed through to production.
=> PP-5299: Don't return next_url and next_url_post links

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java, src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentResource.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java
- The response from getCharge() in PaymentsResource now maps
onto what is expected in publicAPI
- Changes the return type from PaymentResponse to
CollectPaymentResponse
=> PP-5300 Refactor DD connector to remove unused fields on GET Payment

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java, src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentResource.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java
Reverts alphagov/pay-direct-debit-connector#556
=> Revert "PP-5300 Refactor DD connector to remove unused fields on GET Payment"

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java, src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentResource.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java
- Master is currently failing as some changes were lost from tracking in
git, this commit readds those changes to enable it to pass.
=> PP-5300 Fix Master Failures

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java, src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/CollectPaymentResponseMapper.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/SearchMandateDaoIT.java
=> PP-5302: Implement search by bank statement ref, email and name

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/SearchMandateDaoIT.java
=> Pp 5302 search by state and dates

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java, src/main/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParams.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/SearchMandateDaoIT.java
=> Pp 5302 mandate search dao refactor

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java, src/main/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParams.java, src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/SearchMandateDaoIT.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateSearchResourceIT.java
=> Pp 5302 display size and page parameters

pom.xml, src/main/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParams.java, src/main/java/uk/gov/pay/directdebit/mandate/resources/MandateResource.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateSearchResourceIT.java
A little controversially I've put validation within the MandateSearchParams.
=> Pp 5302 validation failures at resource level

src/main/java/uk/gov/pay/directdebit/mandate/resources/MandateResource.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateSearchResourceIT.java
=> PP-5302: Test for non existent gateway account

src/main/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParams.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDaoIT.java
- Changes MandateSearchParams and all instances of it to use a builder
pattern for construction.
=> PP-5302 Add Builder To Mandate Search Params

src/main/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParams.java, src/test/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParamsTest.java
- Add `buildQueryParamsString` to `MandateSearchParams` and add test to ensure
it builds the query string correctly.
=> PP-5302 Make MandateSearchParams implement SearchParams

src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceOutOfOrderMandateEventsIT.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceOutOfOrderPaymentEventsIT.java
Because it’s always good to know things work.
=> PP-5431 Integration test for out-of-order GoCardless payment events

src/main/resources/migrations/00060_create_table_govukpay_events.sql
=> PP-5354 Add govukpay_events table

src/main/java/uk/gov/pay/directdebit/events/dao/GovUkPayEventDao.java, src/main/java/uk/gov/pay/directdebit/events/model/GovUkPayEvent.java, src/test/java/uk/gov/pay/directdebit/events/dao/GovUkPayEventDaoITest.java, src/test/java/uk/gov/pay/directdebit/payments/fixtures/GovUkPayEventFixture.java, src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java
Add DAO with method for persisting a GovUkPayEvent.
=> PP-5354 Add DAO for govukpay_event TABLE

src/main/resources/migrations/00060_alter_tables_mandates_payments_add_columns_state_details_state_details_description.sql
=> Add columns for granular info to mandates and payments tables

src/main/java/uk/gov/pay/directdebit/events/exception/GoCardlessEventHasNoMandateIdException.java, src/main/java/uk/gov/pay/directdebit/events/exception/GoCardlessEventHasNoPaymentIdException.java, src/main/java/uk/gov/pay/directdebit/events/exception/GovUkPayEventHasNoMandateIdException.java, src/main/java/uk/gov/pay/directdebit/events/exception/GovUkPayEventHasNoPaymentIdException.java, src/main/java/uk/gov/pay/directdebit/events/exception/InvalidGovUkPayEventInsertionException.java, src/main/java/uk/gov/pay/directdebit/events/model/GovUkPayEventStateGraph.java, src/main/java/uk/gov/pay/directdebit/payments/services/GovUkPayEventService.java, src/test/java/uk/gov/pay/directdebit/events/model/GovUkPayEventStateGraphTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GovUkPayEventServiceTest.java
Add service to insert GovUkPayEvents along with a graph that defines valid state transitions.
=> PP-5354 Add GovUkPayEvent service

src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java, src/main/java/uk/gov/pay/directdebit/events/model/GovUkPayEvent.java, src/main/java/uk/gov/pay/directdebit/events/services/DirectDebitEventService.java, src/main/java/uk/gov/pay/directdebit/events/services/GoCardlessEventService.java, src/main/java/uk/gov/pay/directdebit/events/services/GovUkPayEventService.java, src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateService.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessHandler.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java, src/test/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/DirectDebitEventServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessEventServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GovUkPayEventServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java, src/test/java/uk/gov/pay/directdebit/tasks/resources/ExpireResourceIT.java, src/test/java/uk/gov/pay/directdebit/tokens/resources/SecurityTokensResourceIT.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessMandateHandlerTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessHandlerTest.java
Insert GovUkPayEvents at the appropriate times.
Move event service classes to the correct package.
=> PP-5354 Insert GovUkPayEvents

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java
=> PP-5302: Date from should be inclusive

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
In the Pact states for mandates and payments, configure each mandate and payment to have state details.
=> PP-5453 Add state details to Pact states

src/main/resources/migrations/00061_alter_table_mandates_not_null_service_reference.sql
=> PP-5472: Make service_reference not null

pom.xml
Reverts alphagov/pay-direct-debit-connector#625
=> Revert "Bump jackson.version from 2.9.9 to 2.10.0.pr1"

src/main/java/uk/gov/pay/directdebit/mandate/model/MandateState.java, src/main/java/uk/gov/pay/directdebit/mandate/model/MandateStatesGraph.java, src/main/java/uk/gov/pay/directdebit/mandate/services/GovUkPayEventToMandateStateMapper.java, src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessEventToMandateStateMapper.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDaoIT.java, src/test/java/uk/gov/pay/directdebit/mandate/model/MandateStatesGraphTest.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java, src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculatorTest.java, src/test/java/uk/gov/pay/directdebit/mandate/services/sandbox/SandboxMandateStateCalculatorTest.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java, src/test/java/uk/gov/pay/directdebit/tasks/resources/ExpireResourceIT.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceMandateActionsIT.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceOutOfOrderMandateEventsIT.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourcePaymentActionsIT.java
Rename EXPIRED -> USER_SETUP_EXPIRED
Rename CANCELLED -> USER_SETUP_CANCELLED
=> PP-5455: Rename expired and cancelled states

src/main/java/uk/gov/pay/directdebit/payments/model/PaymentState.java, src/main/java/uk/gov/pay/directdebit/payments/model/PaymentStatesGraph.java, src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java, src/main/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculator.java, src/main/java/uk/gov/pay/directdebit/payments/services/sandbox/SandboxPaymentStateCalculator.java, src/main/java/uk/gov/pay/directdebit/tasks/services/ExpireService.java, src/main/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResource.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java, src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java, src/test/java/uk/gov/pay/directdebit/payers/resources/PayerResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/fixtures/PaymentFixture.java, src/test/java/uk/gov/pay/directdebit/payments/model/PaymentStatesGraphTest.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentSearchResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentUpdateServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculatorTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/sandbox/SandboxPaymentStateCalculatorTest.java, src/test/java/uk/gov/pay/directdebit/tasks/resources/ExpireResourceIT.java, src/test/java/uk/gov/pay/directdebit/tasks/services/ExpireServiceTest.java, src/test/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResourceIT.java
PENDING -> SUBMITTED_TO_PROVIDER
SUCCESS -> PAID_OUT
=> PP-5455: Rename payment states

src/main/java/uk/gov/pay/directdebit/mandate/model/MandateState.java
=> PP-5455: New mandates SUBMITTED_TO_BANK and EXPIRED

src/main/java/uk/gov/pay/directdebit/notifications/clients/AdminUsersClient.java
- When sendEmail on AdminUsersClient.java is called the logging is
currently poor, this commit makes it have more clarity
=> PP-5438 Improve Logging on SendEmail

src/main/resources/migrations/00064_drop_table_events.sql, src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java
This stored DirectDebitEvents, which are no longer persisted or used.
=> PP-5451 Drop events TABLE

src/main/java/uk/gov/pay/directdebit/mandate/model/MandateState.java, src/main/java/uk/gov/pay/directdebit/payments/services/CollectService.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDaoIT.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceSearchIT.java, src/test/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateServiceTest.java, src/test/java/uk/gov/pay/directdebit/mandate/services/MandateUpdateServiceTest.java, src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java, src/test/java/uk/gov/pay/directdebit/payments/services/CollectServiceTest.java
=> PP-5455: Remove mandate PENDING state

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
=> bau: Revert accidental tag deletion

src/main/java/uk/gov/pay/directdebit/events/model/GovUkPayEventStateGraph.java, src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java, src/test/java/uk/gov/pay/directdebit/events/model/GovUkPayEventStateGraphForMandatesTest.java, src/test/java/uk/gov/pay/directdebit/events/model/GovUkPayEventStateGraphForPaymentsTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/GovUkPayEventServiceTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java
=> PP-5455: Add PAYMENT_CREATED event on new payment

src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessEventToMandateStateMapper.java, src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculator.java, src/main/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessEventToPaymentStateMapper.java, src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculatorTest.java, src/test/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculatorTest.java
=> Pp 5455 go cardless action mappings

src/main/java/uk/gov/pay/directdebit/payments/services/CollectService.java, src/test/java/uk/gov/pay/directdebit/payments/services/CollectServiceTest.java
=> PP-5455: Collect payment when mandate state is SUBMITTED_TO_BANK

src/main/java/uk/gov/pay/directdebit/mandate/model/MandateState.java, src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessEventToMandateStateMapper.java, src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculatorTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceMandateActionsIT.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceOutOfOrderMandateEventsIT.java
And map the GoCardless cancelled event to this new mandate state
=> PP-5455: Add new CANCELLED mandate state

src/main/java/uk/gov/pay/directdebit/payments/api/ExternalPaymentState.java, src/main/java/uk/gov/pay/directdebit/payments/model/PaymentState.java, src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java, src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentSearchResourceIT.java
Rename "started" to "created" and add new "paidout" and "indemnityclaim" external states.
Remove the EXTERNAL_EXPIRED and EXTERNAL_CANCELLED_USER_NOT_ELIGIBLE external states.
=> PP-5475 Update payment external states

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java, src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java, src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/MandateMapper.java, src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java, src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
- This adds the description field as an optional parameter on GET
mandate, as well as adding tests to ensure that it is included in the
return object.
=> PP-5514 Add description to GET Mandate

src/main/resources/config/config.yaml
Reverts alphagov/pay-direct-debit-connector#694
=> Revert "PP-5486 Add Extra NonProxyHosts Configuration"

src/main/java/uk/gov/pay/directdebit/notifications/clients/ClientFactory.java
Reverts alphagov/pay-direct-debit-connector#701
Failing on master. Will resolve tomorrow.
=> Revert "PP-5486: Use the system proxy settings for the Jersey client"

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/api/GatewayAccountResponse.java, src/test/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResourceIT.java
- Adds an organisation field to the gateway account, if it exists, as
well as a test to ensure that it is correctly added.
=> PP-5476 Add Organisation Field To Gateway Account

src/main/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDao.java, src/main/java/uk/gov/pay/directdebit/events/services/GoCardlessEventService.java, src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java, src/test/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDaoIT.java, src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessEventServiceTest.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceMandateActionsIT.java, src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java
Batch updating as opposed to individual event insertion reduces the time taken
to insert events by more than 50%.
=> PP-5567: Use batch update of events

pom.xml
=> bau: we don't actually use guava

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java, src/test/java/uk/gov/pay/directdebit/pact/SelfServiceApiContractTest.java
=> bau: Reduce pact provider test runs

pom.xml, src/main/resources/config/config.yaml
- Adds a logstash dependency to enable JSON logging for direct debit
connector
=> PP-5511 Add Logstash Dependency

pom.xml
=> bau: Remove unused groovy dependency

README.md, pom.xml, src/main/resources/config/config.yaml
- Add a library to allow Sentry config to be dropped into Dropwizard
YAML config
- Add the relevant lines to the YAML config to pull the DSN and
environment out of env vars
=> REP-401: Add Sentry config

pom.xml, src/test/java/uk/gov/pay/directdebit/pact/ContractTestSuite.java
=> PP-5670: Update pay-java-commons library

src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
This is a matter of practicality so as to avoid having to re-do the splunk searches.
=> PP-5735: Rename label to container

pom.xml, src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java, src/main/resources/config/config.yaml
=> PP-5776: Configure server request logs to log in json format

pom.xml, src/main/java/uk/gov/pay/directdebit/filters/LoggingMDCResponseFilter.java
so we can use the correct logging key: https://github.com/alphagov/pay-java-commons/pull/182/files
=> PP-5893: Update pay java commons

pom.xml
- Update the ```maven-jar-plugin``` from 3.1.2 -> 3.2.0
Co-authored-by: Daniel Besbrode <daniel.besbrode@digital.cabinet-office.gov.uk>
=> PP-4573 Update Maven Jar Plugin

pom.xml
- Updates the plugin for ```maven-failsafe``` to the newest version
=> PP-4573 Update maven failsafe plugin

.travis.yml
Adds a simple .travis.yml build configuration for running CI java build tasks.
=> Add .travis.yml CI build configuration

src/main/resources/env-map.yml
Frontend url was incorrectly mapped to card frontend.
=> PP-6085: Fix dd frontend url mapping

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/support/GoCardlessWebhookVerifier.java
- add StandardCharsets.UTF_8 to getBytes so it's not using locale
=> PP-8394  add standard charset to getBytes()
