alphagov/pay-direct-debit-connector

pom.xml

The eclipselink 2.7.0 artifact depends on javax.persistence 2.2.0 and both contain classes that are in the package javax.persistence. However the javax.persistence jar is signed while the eclipselink one is not. So the Java runtime will complain, when loading a class from the package javax.persistence in the eclipselink jar, that it's lack of signing doesn't match with classes already loaded from the same package in the javax.persistence jar.
When running the app, we are receiving:
```
java.lang.SecurityException: class "javax.persistence.PersistenceUtil"'s signer information does not match signer information of other classes in the same package
```
More information:
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=525457
- https://stackoverflow.com/questions/45870753/eclipselink-2-7-0-and- …

Fix EclipseLink and java.lang.SecurityException

---

pom.xml
src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitConfig.java
src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java
src/main/java/uk/gov/pay/directdebit/app/config/GoCardlessFactory.java
src/main/resources/config/config.yaml

This PR adds initial GoCardless SDK integration.
It will use `GDS_DIRECTDEBIT_CONNECTOR_GOCARDLESS_ACCESS_TOKEN` environment variable to initialise sandbox API keys only.
Later, when the partner integration is implemented we should not use `GDS_DIRECTDEBIT_CONNECTOR_GOCARDLESS_ACCESS_TOKEN` and persist the api access tokens in the database.
The changes are based on https://github.com/gocardless/gocardless-pro-java-example

PP-2883 GoCardless client initial integration

---

Dockerfile
update-chamber.sh

- Added CHAMBER_URL build-time argument to the Dockerfile
- Modified update-chamber.sh to reflect the changes
Based on https://github.com/alphagov/pay-selfservice/pull/551

PP-2905 Update Chamber improvements

---

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/config/GoCardlessFactory.java

Do not throw "GoCardless webhook secret is blank" exception (we don't have test webhook secret yet).
Ignore the exception for now and we will discuss should we have dummy value or some kind of condition for dev env.

PP-2883 Do not throw "GoCardless webhook secret is blank" exception

---

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/config/GoCardlessFactory.java
src/main/resources/config/config.yaml

- Rollback RuntimeException for empty webhook secret and add dummy secret
- Temporary added dummy secret in the configuration to avoid blocking `msl -a up`
- Probably we need to add an environment flag and mock the GoCardless SDK if it's not in AWS environment

PP-2883 Rollback RuntimeException for empty webhook secret

---

pom.xml
src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitConfig.java
src/main/java/uk/gov/pay/directdebit/app/config/LinksConfig.java
src/main/java/uk/gov/pay/directdebit/app/config/ProxyConfiguration.java
src/main/java/uk/gov/pay/directdebit/common/dao/DateArgumentFactory.java
src/main/java/uk/gov/pay/directdebit/common/util/RandomIdGenerator.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/TokenDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentRequestMapper.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TokenMapper.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentRequest.java
src/main/java/uk/gov/pay/directdebit/payments/model/Token.java
src/main/resources/config/config.yaml
src/main/resources/migrations.xml
src/main/resources/migrations/00001_create_table_payment_requests.sql
src/main/resources/migrations/00002_create_table_tokens.sql
src/test/java/uk/gov/pay/directdebit/infra/DaoITestBase.java
src/test/java/uk/gov/pay/directdebit/infra/PostgresDockerRule.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestDaoTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/TokenDaoTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/DbFixture.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/PaymentRequestFixture.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/TokenFixture.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java
src/test/java/uk/gov/pay/directdebit/util/NumberMatcher.java
src/test/java/uk/gov/pay/directdebit/util/ZonedDateTimeTimestampMatcher.java
src/test/resources/config/test-it-config.yaml

This PR introduces two new entities, `PaymentRequest` and `Token`, with relative DAOs and test infrastructure.
- `PaymentRequest` and `Token` are modelled according to https://payments-platform.atlassian.net/browse/PP-2841. There is a difference: `payment_provider` is not in the`payment_requests` table, as will be inferred from the gateway account once that is modelled
- The DAOs are built according to JDBI 3 Declarative APIs
- Migrations are currently run before each test (See the `DAOItestBase`'s rules), this will changed once the DB spike is completed and the work is brought in master

PP-2971 Add PaymentRequest and Token entities, with relative DAOs

---

Dockerfile
docker-startup-with-db-migration.sh
src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java

- This will PR makes so that db migrations are _not_ run at deployment time, just locally

PP-2971 Add a separate docker compose script to run migrations

---

src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestEventDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentRequestEventMapper.java
src/main/java/uk/gov/pay/directdebit/payments/exception/UnsupportedPaymentRequestEventException.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEvent.java
src/main/resources/migrations/00003_create_table_payment_request_events.sql
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestDaoTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestEventDaoTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/TokenDaoTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/PaymentRequestEventFixture.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/PaymentRequestFixture.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/TokenFixture.java
src/test/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEventTest.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java

- We support a series of events, which represent a transition between two states. These will be detailed as a graph in a subsequent PR.
- If we try to parse an unsupported event we return a checked exception. And we log a warning - this is because we have no control over which event will arrive from gocardless and we want to make sure we pick the ones we decide to support.

PP-2971 Add payment request events

---

src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEvent.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentStatesGraph.java
src/main/java/uk/gov/pay/directdebit/payments/model/Transaction.java
src/main/resources/migrations/00004_create_table_transactions.sql
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestDaoTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestEventDaoTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/TransactionDaoTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/TransactionFixture.java
src/test/java/uk/gov/pay/directdebit/payments/model/PaymentStatesGraphTest.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java

- There are a few differences from the proposed database design.
1. `status` is `state`, to be consistent with the rest (ie. `PaymentState`).
This was something that bit us in connector, as we started to have both status and state , and it became quickly very confusing.
1. operation` has been renamed to`type`. This is to be consistent with the rest, as we already have a payment event type, and it makes sense to have a transaction type, too.
1. `gateway_transaction_id` has been removed, as it is gocardless specific and should be part of another table

PP-2971 Create Transactions

---

src/main/resources/migrations/00001_create_table_payment_requests.sql
src/main/resources/migrations/00002_create_table_tokens.sql
src/main/resources/migrations/00003_create_table_payment_request_events.sql
src/main/resources/migrations/00004_create_table_transactions.sql

- Add missing Foreign keys using naming convention suffix '_fk'.
- Renamed index to use suffix '_idx'
- Add Index to 'tokens.secure_redirect_token' since is the value used to query tokens + deletes.

PP-2073 Database add foreign keys

---

src/main/resources/config/config.yaml

Providing a database host as url + port makes things easier
for ecs, and is also nicer anyway I reckon.

PP-2850 Don't hardcode db port

---

src/main/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResource.java
src/main/java/uk/gov/pay/directdebit/payers/resources/PayerResource.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestService.java
src/main/java/uk/gov/pay/directdebit/tokens/resources/SecurityTokensResource.java
src/test/java/uk/gov/pay/directdebit/payers/resources/PayerResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentRequestResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentRequestServiceTest.java
src/test/java/uk/gov/pay/directdebit/tokens/resources/SecurityTokensResourceIT.java

- Partition payment requests by `/{accountId}`
- Use dash instead of underscore for consistency with the confirm resource
- Renamed chargeTokenId to just `token`

PP-3106 Reassign Payer resource to correct url

---

src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestService.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentRequestResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentRequestServiceTest.java

- Demoservice expects `chargeTokenId` back from connector. Sadness. Won't change demoservice itself right now because we want it to be transparent as to which payment type is in use

PP-3106 Rename token back to chargeTokenId

---

Dockerfile
docker-startup.sh
run-with-chamber.sh

Cater for 3 different startup scenarios
- dev migrate db and start
- start only
- migrate db only
Ensure Docker deploys the new script run-with-chamber script
Chamber executes docker-startup.sh which has logic for the
above-mentioned scenarios
We are keeping the docker-startup-with-db-migration.sh to
prevent breakages whilst we transition
TODO once we are happy with the new system
- remove the docker-startup-with-db-migration.sh and reference
in Dockerfile
- remove the RUN_APP VALUE variable in docker-startup.sh to ensure the
script fails in the event that the new variable is not set. The
RUN_MIGRATION will only be set by microservices that have a db.

PP-3174 Implement database migrations for ECS

---

Jenkinsfile

We now have a e2e direct-debit-specific profile. This will run only direct debit end to end tests, similar to how's done with products.

PP-2939 Run direct debit e2e tests on merges

---

Jenkinsfile

The standard run-end-to-end-tests job is throttled to 2 concurrent builds max. This is slowing down a lot direct debit, as we often have to wait for 40+ min for other builds to finish, when we don't need to.
There is a new job in Jenkins which just runs dd tests, and it is not throttled.

PP-2939 Use the new direct debit run e2e job on PR merge

---

Jenkinsfile

- `jobName` was picked up as `exclude` - the power (?) of defaults

PP-2939 Fix exclude vs jobname in jenkinsfile

---

Dockerfile

We should use the openjdk image from govukpay, this will give us chamber as well as our other additions.

BAU: Use govukpay openjdk image

---

src/main/resources/migrations/00007_create_table_gateway_accounts.sql

Adding the `gateway accounts` table to dd connector. The gateway account, in addition to all the fields already present in connector, has an external id we generate.

PP-3061 Add gateway accounts table to the db

---

src/main/resources/migrations/00008_alter_table_gateway_accounts_external_id.sql

- we want to be able to namespace external ids by prefixing them with `DIRECT_DEBIT:<token>`. We need a longer external id. Adminusers already stores gateway ids as a VARCHAR(255).

PP-3061 Make gateway_accounts.external_id a VARCHAR(255)

---

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/api/CreateGatewayAccountValidator.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/api/GatewayAccountResponse.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/exception/GatewayAccountNotFoundException.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/model/GatewayAccount.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResource.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountParser.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountService.java
src/main/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResource.java
src/main/java/uk/gov/pay/directdebit/payers/resources/PayerResource.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentRequestResource.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestService.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/api/CreateGatewayAccountValidatorTest.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResourceIT.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountParserTest.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentRequestResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentRequestServiceTest.java

- We are generating an *external id* for the gateway account, and assuming that scripts / self service / public auth will use that, rather than the internal id. This is needed because we now have gateway accounts in two places (cc and dd connectors), and using  internal ids will cause clashes in accounts, as the ids are generated sequentially from two different dbs.
We are going to raise a few other PRs in those microservices to handle external ids and internal ids at the same time.
- When we have to do any operation on a charge/payment request, we first check if the gateway account associated to that resource exists. If not, we throw a `GatewayAccountNotFoundException`
- When creating a gateway account, we are assuming `service_name`, `payment_provider` and `type` are mandatory.
Note: …

PP-3061 Add gateway accounts services and resource

---

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmService.java
src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEvent.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentState.java
src/main/java/uk/gov/pay/directdebit/payments/model/SandboxPaymentStatesGraph.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestEventService.java
src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResource.java
src/main/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResource.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/dao/TransactionDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEventTest.java
src/test/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResourceIT.java

This PR adds a new `POST /v1/webhooks/sandbox` endpoint which will be used to emulate the asynchronous behaviour of the states of transactions.
Once called it will change all `PENDING_DIRECT_DEBIT_PAYMENT` state transactions to their `SUCCESS` state.
Currently, we do not differentiate between sandbox and external providers in transactions. This will be added once we integrate the external provider.
with @rauligs 
Note: to be merged once https://github.com/alphagov/pay-endtoend/pull/502 and https://github.com/alphagov/pay-scripts/pull/570 and https://github.com/alphagov/pay-stubs/pull/71 are merged

PP-3237 Sandbox webhook

---

src/main/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResource.java
src/main/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmService.java
src/main/java/uk/gov/pay/directdebit/payers/resources/PayerResource.java
src/main/java/uk/gov/pay/directdebit/payers/services/PayerService.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java
src/main/java/uk/gov/pay/directdebit/payments/exception/PaymentRequestNotFoundException.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestService.java
src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmServiceTest.java
src/test/java/uk/gov/pay/directdebit/payers/resources/PayerResourceIT.java
src/test/java/uk/gov/pay/directdebit/payers/services/PayerServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/dao/TransactionDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentRequestServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java

- After introducing gateway accounts in dd connector, we started by validating that a gateway account exists when creating a payment request.
It is also necessary  to check that a charge belongs to a specific gateway account before acting on it later on (e.g. retrieving it, checking all the transactions, and so on)
- This PR introduces additional checks in all endpoints which are of the shape of `/accounts/{account_id}/someresource/{charge_id}` by making sure that the gateway account associated to the charge is the correct one

PP-2886 Check that a charge belongs to a gateway account in every resource

---

src/main/resources/migrations/00009_create_table_gocardless_customers.sql

This will be used to store gocardless-specific ids, so that we don't pollute our domain model.

PP-2886 Add db table for gocardless' customers

---

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java

- When a failure happens in their client, GoCardless do wrap IOException, hiding the root cause of the failure. In order to have a bit more info when things go wrong, this PR adds logging of the cause, if present.

PP-3443 Log cause of gocardless failure, not just the exception message

---

src/main/resources/migrations/00012_create_table_gocardless_events.sql

Adding a table to store gocardless events. This will be used to keep a record of every single webhook we receive from gocardless, even if we don't handle it.
- `payment_request_events_id` is a foreign key to the `payment_request_events` table.
It is nullable because we are not going to always have an "internal" event, for a
received gocardless event

PP-2885 Add table for gocardless events

---

src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/directdebit/junit/PostgresTestDocker.java

- Changed the database name of Direct Debit connector to be the same as defined in https://github.com/alphagov/pay-infra/blob/e391505b4e164d94a0db590f9e2b1f670c04fc32/provisioning/terraform/modules/pay_microservices/directdebit-connector/directdebit-connector.tf#L43

PP-2897 Change Direct Debit database to be consistent

---

src/main/java/uk/gov/pay/directdebit/payers/api/CreatePayerValidator.java
src/main/resources/migrations/00013_alter_table_payers_nullable_address.sql
src/test/java/uk/gov/pay/directdebit/payers/api/CreatePayerValidatorTest.java
src/test/java/uk/gov/pay/directdebit/payers/resources/PayerResourceIT.java

- We will still optionally accept and store address if these fields appear in the request, but if they are not there they are not validated so they are nullable.
- If any adress fields ('adress_line_1', 'adress_line_2', 'postcode', 'country_code', 'city') appears in the payload is still being validated.

PP-3479 Make address non required

---

src/main/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmService.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestEventDao.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEvent.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentStatesGraph.java
src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestEventService.java
src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java
src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessAction.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResource.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentRequestEventDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/ConfirmationDetailsFixture.java
src/test/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEventTest.java
src/test/java/uk/gov/pay/directdebit/payments/model/PaymentStatesGraphTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentRequestEventServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceIT.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessMandateHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java

Handle events:
- Mandates: 'created', 'submitted','active'
- Payments: 'created', 'submitted', 'confirmed', 'paid_out'
- Transitions are pending, this is because we need to think if for one off we should add mandate transitions at all or just store the events and only _listen_ to payment ones.

PP-3238 Add happy path events handling

---

src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java

Unfortunately to go from mandate id to transaction we have to do a whole lotta joins.

PP-3443 Fix join for transaction dao when finding a transaction by mandate id

---

src/main/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientWrapper.java
src/test/java/uk/gov/pay/directdebit/util/GoCardlessStubs.java
src/test/resources/it/requests/gocardless/create-payment.json
src/test/resources/it/responses/gocardless/create-payment-success.json

We don't need to send our payment reference to GoCardless right now. There are rules surrounding that (ie. max length) and we need to figure out the right way of dealing with that.

PP-3238 Do not set payment reference in GoCardless

---

src/main/resources/migrations/00014_alter_table_gocardless_payments_charge_date.sql

This is sent to us from gocardless and it's going to be used in the body of the payment confirmation email we send to the user.

PP-2810 Add charge date column to gocardless payments table

---

src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessResourceType.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEvent.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestEventService.java
src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java
src/test/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEventTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentRequestEventServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java

- Paid is the only possible action for payout - so we are handling that in our payment handler
instead of creating a new handler just for that one action
- Assumption is that the payment has already been set to `PAID_OUT` (meaning the money has left the user's bank account) before receiving a payout `PAID` event (meaning the money has left gocardless' bank account in favour of the service's).
If this assumptions proves to be incorrect, we might need to revisit our handler
- Added some tests for unrelated events which were missing

PP-3238 Handle payout paid event

---

src/main/java/uk/gov/pay/directdebit/app/config/LinksConfig.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/GoCardlessPaymentMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/model/GoCardlessPayment.java
src/main/java/uk/gov/pay/directdebit/notifications/config/NotifyClientFactory.java
src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java
src/main/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientWrapper.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java
src/main/java/uk/gov/pay/directdebit/payments/model/Transaction.java
src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java
src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java
src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/directdebit/app/config/LinksConfigTest.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/GoCardlessPaymentFixture.java
src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/TransactionFixture.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java
src/test/resources/config/test-it-config.yaml

- When a user confirms a payment, we send out an email to their address. This emails contains a few details about the payment they are about to set up. A few of them are pretty self-explanatory, like `service name`, `amount`, `payment reference`, `last two digits of the bank account`
- `colelction date` is a bit more interesting. GoCardless sends back to us the earliest charge date (or the one you set up yourself, in case of scheduled / ad hoc payments), so we are using that to give an indication to the user as to when the payment will be taken
- `SUN` is not filled in right now, as we still have to decide which one will be used
- `merchant details` are not filled in either. This is because merchant details are at a service level and this is becoming increasingly not compatible with our …

PP-2810 Send email to user when a payment is confirmed

---

src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java

Change:
```java
new InvalidStateException(format("Could not find payment pending event for payment request with id: {}", transaction.getPaymentRequestExternalId()))
```
… to:
```java
new InvalidStateException("Could not find payment pending event for payment request with id: " + transaction.getPaymentRequestExternalId()))
```
… which will actually output the ID, not a literal `{}`.

Fix exception message (String.format uses %s not {} as placeholder)

---

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParser.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParserTest.java

- There was no `PAYOUTS` case when extracting the resource id, so the
webhook for payout paid was not handled properly

Fix payout paid webhook not parsed properly

---

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java

- When mandate/payment handlers for webhooks throw an exception, the exception mapper
of Dropwizard kicks in and the execution is interrupted. As we were storing events after handling them, we were missing quite a few of them.
- We are now storing events immediately after parsing the webhook, so that whatever happens
in the handler, we are already covered
Create one or more webhooks in stubs and send them to dd connector. DD connector logs will show an error. Nevertheless, we should see in the database all the events.

PP-3828 Make sure we store events even when the handlers throw an exception

---

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/exception/MandateNotFoundException.java
src/main/java/uk/gov/pay/directdebit/notifications/config/NotifyClientFactory.java
src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java
src/main/java/uk/gov/pay/directdebit/payments/exception/ChargeNotFoundException.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEvent.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestEventService.java
src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/model/PaymentRequestEventTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentRequestEventServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessMandateHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java
src/test/resources/config/test-it-config.yaml

- Registering a specific event when a payment is submitted by GC to the bank
- When we receive a mandate cancelled from GoCardless, we will act depending on two different scenarios:
- The payment associated to the mandate is CREATED, this means it has not been submitted to the bank by GC. This also means they won't send us a webhook to tell us that the payment failed, so we have to update the charge status ourselves
- The payment associated to the mandate is SUBMITTED. We don't update the charge status ourselves as we will receive a webhook from GC telling us what happened to it.
Right now we have no concept of a lifecycle for mandates, like we do for payments. I will raise another PR to add that graph. Once that is done, mandate cancelled will update the status of a mandate.

PP-3361 Handle mandate cancelled event

---

Dockerfile

When chamber moved into the base image, we didn't fully clean up. Remove this stray code which adds and then removes openssl.
Also, use --no-cache more when running apk

Pp 3666 remove openssl

---

src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/api/PaymentRequestResponseTest.java

Removes a few warnings when you do a build

Use undeprecated methods instead of deprecated ones in tests

---

src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmService.java
src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java
src/main/java/uk/gov/pay/directdebit/payers/api/PayerParser.java
src/main/java/uk/gov/pay/directdebit/payers/services/PayerService.java
src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentRequest.java
src/main/java/uk/gov/pay/directdebit/payments/model/Transaction.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentRequestEventService.java
src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/main/java/uk/gov/pay/directdebit/tokens/api/TokenResponse.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
src/test/java/uk/gov/pay/directdebit/payers/api/PayerParserTest.java
src/test/java/uk/gov/pay/directdebit/payers/services/PayerServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/TransactionDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/TransactionFixture.java
src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java
src/test/java/uk/gov/pay/directdebit/tokens/services/TokenServiceTest.java

`Transaction` constructor refactoring to use `PaymentRequest` object.
See commits for more details.

PP-3545 Transaction constructor refactoring

---

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java

Log an error instead of warning when we receive unknown webhook actions

PP-3362 Log an error instead of warning when we receive unknown webhook actions

---

src/main/java/uk/gov/pay/directdebit/common/validation/FieldSizeValidator.java
src/main/java/uk/gov/pay/directdebit/mandate/api/ConfirmDetailsRequestValidator.java
src/main/java/uk/gov/pay/directdebit/mandate/model/ConfirmationDetails.java
src/main/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResource.java
src/main/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmService.java
src/main/java/uk/gov/pay/directdebit/payers/api/CreatePayerValidator.java
src/main/java/uk/gov/pay/directdebit/payers/model/Payer.java
src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitPaymentProvider.java
src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java
src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java
src/test/java/uk/gov/pay/directdebit/mandate/api/ConfirmDetailsRequestValidatorTest.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/ConfirmPaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/PaymentConfirmServiceTest.java
src/test/java/uk/gov/pay/directdebit/payers/dao/PayerDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/ConfirmationDetailsFixture.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java

https://github.com/alphagov/pay-direct-debit-frontend/pull/77 is now sending confirmation details (account number and sort code) to connector. 
This PR creates a payer using those details. This is because with the new call layout we don't have non-hashed details anymore when creating a bank account in our payment provider.

PP-3701 Create payer using confirm details from frontend

---

src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java

GC might throw an exception if the validation fails. We need to handle this properly instead of relying on the exception mapper to catch it and return an internal server error.

PP-3714 Catch exceptions from gc when validating bank account details

---

src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java

- When submitting the same direct debit details several times for the
same `payment_request`, we were registering state transition events even
if the transition was invalid. This action didn't change the status of
the transaction, but was registering an event. Not it doesn't.
- A tiny spelling correction as the action happened before that line

PP-3700 Prevent payment request event duplication

---

pom.xml

Upgrade GoCardless SDK version from `3.3.0` to `3.4.0`

PP-3776 Upgrade GoCardless SDK version

---

Jenkinsfile

Silvia is in the mioddle of orchestrating the apocalypse, and does not
need these pesky tests in her way. This points the Jenkinsfile at a branch
of pay-jenkins-library that has no-ops for dd tests.

Use branch of pay-jenkins-library that does not run dd tests

---

src/main/resources/migrations/00023_drop_table_payment_requests.sql
src/main/resources/migrations/00024_alter_table_mandate_payer_id.sql
src/main/resources/migrations/00025_alter_table_transactions.sql
src/main/resources/migrations/00026_alter_table_payers_payment_request_id.sql.sql
src/main/resources/migrations/00027_create_table_events.sql
src/main/resources/migrations/00028_alter_table_tokens.sql

- Removing payment_request_id from tables, as we now assume there's
a mandate_id to link tables together
- Drop table payment_requests
- Drop constraint NOT_NULL for type of transaction, this will be dropped in another PR
- Adding a new table events, will drop payment_request_events in another PR

PP-3676 Cleanup migrations after updating the data model (part 1)

---

src/main/resources/migrations/00029_alter_table_gocardless_events.sql

- Add `internal_event_id` to gocardless event and make it reference the new `events` table. `payment_request_event_id` will be dropped in the next PR

PP-3676 Add internal_event_id in gocardless events pointing to the new events table

---

src/main/java/uk/gov/pay/directdebit/payments/dao/EventDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/GoCardlessEventDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java
src/test/java/uk/gov/pay/directdebit/payments/dao/GoCardlessEventDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/EventFixture.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/GoCardlessEventFixture.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/TransactionFixture.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java

- Use the new table `events` instead of `payment_requests_events`
- Stop using type in transactions
- Both `type` and the table `payment_requests_events` will be dropped in the next pr

PP-3676 Use the new table events instead of payment_requests_events

---

src/main/resources/migrations/00030_alter_table_transactions_drop_type.sql
src/main/resources/migrations/00031_drop_table_payment_request_events.sql

- transaction type is not used (it's always charge) 
- we are using a table called `events` now, so `payment_request_events` can be dropped

PP-3676 Drop type from transactions and drop payment_request_events

---

src/main/resources/migrations/00032_alter_table_mandates_add_column_mandate_reference.sql
src/main/resources/migrations/00033_alter_table_mandates_add_column_service_reference.sql

- Added `mandate_reference` column which will replace `reference` column in the next releases.
This is necessary to distinguish between mandate reference and the future service reference.
- Added `service_reference` column which will hold optional service reference value.
with @georgeracu

PP-3676 Update mandates table schema to handle references

---

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java

Mandate needs to link to a valid gateway account.

PP-3677 Make sure mandate has the right gateway account id for pact

---

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java

It looks like pact does not hold state, so to make sure we insert both gateway accounts and mandates it might be necessary to add a state that contains both.

PP-3677 Make sure mandate has the right gateway account id for pact, for real. Again.

---

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/model/MandateState.java
src/main/java/uk/gov/pay/directdebit/mandate/model/MandateStatesGraph.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitEvent.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentStatesGraph.java
src/main/java/uk/gov/pay/directdebit/payments/services/DirectDebitEventService.java
src/main/java/uk/gov/pay/directdebit/tasks/resources/ExpireResource.java
src/main/java/uk/gov/pay/directdebit/tasks/services/ExpireService.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/MandateFixture.java
src/test/java/uk/gov/pay/directdebit/mandate/model/MandateStatesGraphTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/tasks/resources/ExpireResourceTest.java
src/test/java/uk/gov/pay/directdebit/tasks/services/ExpireServiceTest.java

… end-point (see PP-3647 and pull request #176 which created this service with the initial payment expiry functionality).
Following the implementation of the existing payment expiry logic it:
- finds all mandates in a state prior to PENDING and created more than 90 minutes ago. Note that eligible states are determined from the MandateStatesGraph.getPriorStates which was
introduced in the previous PR for payments (see above)..
- Updates the status of each mandate to EXPIRED and creates an event MANDATE_EXPIRED_BY_SYSTEM.
- Adds the number of expired mandates the response.
The existing implementation and merged PR for expiring payments can be viewed at:
https://github.com/alphagov/pay-direct-debit-connector/pull/176
@mrlumbu

This change adds the capability to expire mandates to the ExpireResourse

---

src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewListResponse.java
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResponse.java
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewValidator.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentViewMapper.java
src/main/java/uk/gov/pay/directdebit/payments/links/Link.java
src/main/java/uk/gov/pay/directdebit/payments/model/ViewPaginationBuilder.java
src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResource.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentViewService.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
src/test/java/uk/gov/pay/directdebit/payments/api/PaymentViewValidatorTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParamsTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceITest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentViewServiceTest.java

Payment view should be able to be searched by a mandate id. Search response should also mirror to a logical extent that of connector search, eg paginations, total and count.
- add mandate_id and and query string generation to `PaymentViewSearchParams`
- refactor `PaymentViewSearchParams` to use `withXXXParam` instead of an unreadable constructor
- add `withUriInfo` to `PaymentViewService` to enable the service to generate links
- introduce `Link` class
- add feature to searching to include the total number of records for a given search
- refactor searching to include the number of records on the given page and the page number
- add `ViewPaginationBuilder` (to mirror connector's search pagination)
- add relevant Pact test
- add relevant tests

PP-3679 Refactor search transactions to include mandate_id

---

src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResource.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceITest.java

this change is needed to hide mandate_id from public api
- change mandate_id to agreement on `PaymentViewResource` and `PaymentViewSearchParams.buildQueryParamString()`
- update relevant test

PP-3679 Change endpoint queryparam from mandate_id to agreement

---

src/main/java/uk/gov/pay/directdebit/mandate/api/CreateMandateResponse.java
src/main/java/uk/gov/pay/directdebit/mandate/api/GetMandateResponse.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/MandateFixture.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java

- Added `mandate_reference` to response from `createMandate()` and `getMandate()` endpoints
- Added `service_reference` to response from `getMandate()` endpoints
with @danailminchev

PP-3922 Add mandate reference to API response

---

pom.xml
src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java
src/main/java/uk/gov/pay/directdebit/events/dao/DirectDebitEventSearchDao.java
src/main/java/uk/gov/pay/directdebit/events/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/directdebit/events/service/DirectDebitEventsSearchService.java
src/main/java/uk/gov/pay/directdebit/payments/dao/DirectDebitEventDao.java
src/main/java/uk/gov/pay/directdebit/payments/model/CustomDateSerializer.java
src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitEvent.java
src/main/java/uk/gov/pay/directdebit/payments/params/DirectDebitEventSearchParams.java
src/test/java/uk/gov/pay/directdebit/payments/resources/GetDirectDebitEventsTest.java

This adds a new resource to search for events by mandate id, transaction id, before date and after date. Also accepts page size and page number parameters. All parameters are optional and the default page size is 500 (this is also the maximum page size).
Pagenation is done using OFFSET and LIMIT as part of the db query as per existing patterns found in DD Connector.
@oswaldquek

PP 3680 search events

---

src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResource.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java

- refactor Pact test to try to use mandate_id by either agreement or agreement_id
- refactor PaymentViewResource to accept both agreement and agreement_id

PP-3679 refactor to accept both agreement and agreement_id as queryparams part 1

---

docs/api_specification.md
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResource.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceITest.java

- remove backwards compability 'mandate' from search queryparams
- update relevant tests/api docs
- refactor `PaymentViewService` to use String literals instead of constants

PP-3679 Remove agreement from search params

---

src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/ConfirmMandateSetupResourceIT.java
src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/TransactionResourceIT.java

Our email provider fixed the bug where the asterisks were truncated to two `**` if they are defined in the email provider's template.
Now we can move them to the template definition.
We will clean-up the commented tests in the next PR as well
with @georgeracu

PP-3676 Remove asterisks from email payloads

---

src/main/java/uk/gov/pay/directdebit/mandate/model/ConfirmationDetails.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/payers/api/PayerParser.java
src/main/java/uk/gov/pay/directdebit/payers/model/BankAccountDetails.java
src/main/java/uk/gov/pay/directdebit/payers/model/BankAccountDetailsParser.java
src/main/java/uk/gov/pay/directdebit/payers/model/SortCode.java
src/main/java/uk/gov/pay/directdebit/payers/resources/PayerResource.java
src/main/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientFacade.java
src/main/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientWrapper.java
src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/payers/model/SortCodeTest.java
src/test/java/uk/gov/pay/directdebit/payers/resources/PayerResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientFacadeTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/ConfirmationDetailsFixture.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceOneOffTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java

The `SortCode` object represents a UK bank account sort code with no dashes or spaces e.g. `"123456"`. It performs a check when it’s constructed to ensure that it consists of exactly six Arabic numerals.
It’s safe to do this in most cases because `SortCode` objects are usually only ever created to represent data in requests and most of our resources ensure the sort codes match the correct format before the `SortCode` objects are created.
The exception was the bank account details validation resource, which performed no such checks. This has now been updated to check that the `sort_code` and `account_number` fields are present and that they are both numeric strings with appropriate lengths. While this change has may cause some behaviour changes, they won’t affect us in practice because …

PP-3942 Introduce SortCode object

---

src/main/java/uk/gov/pay/directdebit/mandate/model/ConfirmationDetails.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/payers/api/PayerParser.java
src/main/java/uk/gov/pay/directdebit/payers/model/AccountNumber.java
src/main/java/uk/gov/pay/directdebit/payers/model/BankAccountDetails.java
src/main/java/uk/gov/pay/directdebit/payers/model/BankAccountDetailsParser.java
src/main/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientFacade.java
src/main/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientWrapper.java
src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessService.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/payers/model/AccountNumberTest.java
src/test/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientFacadeTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/ConfirmationDetailsFixture.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceOneOffTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java

The `AccountNumber` object represents a UK bank account number with no dashes or spaces e.g. `"12345678"`. It performs a check when it’s constructed to ensure that it consists of six to eight Arabic numerals inclusive. It’s safe to do this because `AccountNumber` objects are only ever created to represent data in requests and our resources ensure the account numbers match the correct format before the `AccountNumber` objects are created.
Note that there’s no guarantee that an `AccountNumber` object actually represents a real bank account.
The `accountNumber` field in the `Payer` class remains a `String` rather than becoming an `AccountNumber` object because we hash the account number before passing it to the `Payer` constructor (except in some tests), so it isn’t actually an account …

PP-3942 Introduce AccountNumber

---

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDao.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResource.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountService.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResourceIT.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/GatewayAccountDaoIT.java
src/test/resources/config/test-it-config.yaml
src/test/resources/logback.xml

same as https://github.com/alphagov/pay-connector/pull/633
but for dd
basically
them all
solo @tlwr

PP-3928: Account list endpoint filter

---

Jenkinsfile

Because we weren't running pact provider tests on master branch, the 'Pact Tag' build
step wasn't tagging anything, as the commit on the master branch is different
to that of the PR (where provider tests were being run). A side effect of this
is that when checking publicapi is ok to deploy, the pact broker isn't checking
the compatibility between publicapi and direct-debit-connector.
@oswaldquek

bau: Run pact provider tests on master branch

---

pom.xml
src/main/java/uk/gov/pay/directdebit/events/api/DirectDebitEventsPagination.java
src/main/java/uk/gov/pay/directdebit/events/api/DirectDebitEventsResponse.java
src/main/java/uk/gov/pay/directdebit/events/dao/DirectDebitEventSearchDao.java
src/main/java/uk/gov/pay/directdebit/events/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/directdebit/events/service/DirectDebitEventsSearchService.java
src/main/java/uk/gov/pay/directdebit/payments/params/DirectDebitEventSearchParams.java
src/test/java/uk/gov/pay/directdebit/events/api/DirectDebitEventsPaginationTest.java
src/test/java/uk/gov/pay/directdebit/events/resources/GetDirectDebitEventsTest.java
src/test/java/uk/gov/pay/directdebit/junit/PostgresTemplate.java
src/test/java/uk/gov/pay/directdebit/payments/resources/GetDirectDebitEventsTest.java

Improved the pagination for event search to include links to first, last, next, self and previous pages. This also introduces "count" as the number of results in the returned page and "total"  as the total number of results available for the parameters provided (e.g. across all pages).
This follows the pattern implemented for Payments search. 
@oswaldquek

Pp 3680 events pagination

---

src/test/java/uk/gov/pay/directdebit/junit/PostgresTestContainer.java
src/test/java/uk/gov/pay/directdebit/junit/PostgresTestDocker.java

Docker for mac is connected to over a unix socket rather than TCP. The postgres setup code
attempts to calculate the hostname of the postgres server. Rather than doing that, we can use
the docker class itself, which knows the hostname that it's running on. This means we can delete
a bunch of code.
I've only tested this on docker-for-mac so I'd appreciate if someone could test it on a docker-toolbox setup as well.
To use with docker for mac, you need to ensure that there are no `DOCKER_*` env vars set in your run configuration, and also that intellij is not propagating the env vars through from its environment.

BAU: Make tests which use DB work with docker for mac

---

src/main/resources/migrations/00035_alter_table_gateway_accounts_add_access_token.sql
src/main/resources/migrations/00036_alter_table_gateway_accounts_add_organisation.sql

Add access_token and organisation columns to the Direct Debit connector gateway_accounts table (initially unpopulated).
- create 2 new alter table scripts to add the columns
Run msl -l up locally and check logs and/or db that columns are present in the table

PP-3961 Add access_token and organisation columns to gateway_accounts

---

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/common/exception/PreconditionFailedException.java
src/main/java/uk/gov/pay/directdebit/common/exception/PreconditionFailedExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/api/CreateMandateRequestValidator.java
src/main/java/uk/gov/pay/directdebit/mandate/model/MandateType.java
src/main/java/uk/gov/pay/directdebit/mandate/resources/MandateResource.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/payments/exception/InvalidMandateTypeException.java
src/main/java/uk/gov/pay/directdebit/payments/resources/TransactionResource.java
src/test/java/uk/gov/pay/directdebit/mandate/api/CreateMandateRequestValidatorTest.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java

- We have already the create payment endpoint which creates a one-off mandate and
a payment.
We do not want to allow creation of one-off mandates from the create agreement
endpoint as this will be used for recurring payments.

PP-3835 Do not allow creation of ONE_OFF mandate from create agreement endpoint

---

src/main/resources/migrations/00035_alter_table_events_add_external_id.sql
src/main/resources/migrations/00037_alter_table_events_add_external_id.sql

- add 'if not exists' to liquibase script
- rename script to follow logical numbering
- run `msl -l up` locally on branch. make sure that `external_id` in `events` exists
- logs should show that the script ran but no action were taken

BAU fix db script breakage

---

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/dao/mapper/GatewayAccountMapper.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/model/GatewayAccount.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/model/PaymentProviderAccessToken.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/model/PaymentProviderOrganisationIdentifier.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/MandateMapper.java
src/main/java/uk/gov/pay/directdebit/payments/dao/TransactionDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java
src/test/java/uk/gov/pay/directdebit/payments/dao/GatewayAccountDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/GatewayAccountFixture.java

Add `accessToken` and `organisation` fields to the `GatewayAccount` object and populate them with the values of the (nullable) `access_token` and `organisation` columns when de-persisting a `GatewayAccount` entity from the database.
Introduce specific types to represent access tokens and organisation identifiers rather than using strings.
No changes to `GatewayAccountParser` because we do not currently support specifying an access token or organisation identifier when creating a gateway account from a JSON payload.
No changes to `GatewayAccountResponse` because we there’s no need for anyone outside of Direct Debit connector to know about these values (in particular, the access token must be kept secret).
On `GatewayAccount`, I made the getters for the new fields return `Optional`s. This …

PP-3962 Read in gateway account access token and organisation

---

pom.xml
src/main/java/uk/gov/pay/directdebit/events/api/DirectDebitEventExternalView.java
src/main/java/uk/gov/pay/directdebit/events/api/DirectDebitEventsPagination.java
src/main/java/uk/gov/pay/directdebit/events/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/directdebit/payments/dao/DirectDebitEventDao.java
src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitEvent.java
src/main/java/uk/gov/pay/directdebit/payments/params/DirectDebitEventSearchParams.java
src/test/java/uk/gov/pay/directdebit/events/api/DirectDebitEventsPaginationTest.java
src/test/java/uk/gov/pay/directdebit/events/resources/GetDirectDebitEventsTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/DirectDebitEventFixture.java

This corrects the url search parameters to match convention.
- `after` becomes `from_date`.
- `before` becomes `to_date`.
- `page_size` becomes `display_size`.
Also removed Lombok from the project after a team discussion and decision. 
@oswaldquek

PP-3680 Correcting parameter names for consistency.

---

docs/api_specification.md
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewValidator.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDao.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentState.java
src/main/java/uk/gov/pay/directdebit/payments/model/ViewPaginationBuilder.java
src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResource.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentViewService.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/model/ViewPaginationBuilderTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceITest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentViewServiceTest.java

- add sql generation for `state` using mapping from `ExternalPaymentState`
- handle external states from resource level downwards
- fix pagination (it's page and not page_number)
- fix bug in calculating next/last/prev page
- update docs
- add/update relevant tests
- fix pagination url (no & after ?)
- added unit tests for `ViewPaginationBuilder`
- refactor `ViewPaginationBuilder` (remove unnecessary list of PaymentViewResultResponse
with @SandorArpa

PP-3646 Implement `state` search and fix pagination

---

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResource.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountService.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountServiceTest.java

- Tidy up `GatewayAccountResource` to use `GatewayAccountService` for `/v1/api/accounts` and `/v1/frontend/accounts` endpoints
- Merged `GatewayAccountService.getAllGatewayAccounts` and `GatewayAccountService.getGatewayAccounts` into one method
with @SandorArpa

PP-3966 Refactor `GatewayAccountResource` to use `GatewayAccountService`

---

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParser.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java

- At the moment we have a sandbox account with GoCardless and they
do not send the field `organisation` in the request so this makes our
webhooks to fail. Following stories will upgrade our GoCardless account
to a Partner account and then we will have `organisation` in the payload.
To unblock other stories I left the logic in place, but replaced the
field with `null`, in case it doesn't exist.
- The todo's should be removed in later stories and field `organisation` should be made mandatory.

PP-3965 Disable manadatory organisation

---

src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java
src/main/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientFactory.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/ConfirmMandateSetupResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/clients/GoCardlessClientFactoryTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/GatewayAccountFixture.java
src/test/java/uk/gov/pay/directdebit/payments/resources/TransactionResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceOnDemandTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceOneOffTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
src/test/java/uk/gov/pay/directdebit/util/GoCardlessStubs.java

After introducing partner integration we are going to instantiate a client for each gateway account, using their access token (which we store).
For now, because partner integration is not yet done, if there's no access token we use the one coming from the config.

PP-3965 Instantiate a gocardless client for each gateway account

---

src/main/java/uk/gov/pay/directdebit/events/api/DirectDebitEventsPagination.java

- Fix bug which incorrectly sets the last_page page number to 0 if the total is 0.
It should be 1.

PP-3680 Fixed pagination when total is 0

---

src/main/resources/migrations/00038_alter_table_mandates_add_column_creditor_id.sql

- We need creditor id to query our provider for the creditor which will have the SUN (Service User Number).
- We make it varchar 255 to be future proof, but the current value is 18 characters.
with @danworth

PP-4002 Add creditor id to mandates

---

src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/OnDemandMandateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/OneOffMandateService.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/OnDemandMandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/OneOffMandateServiceTest.java

- Added check for valid state transition in OneOffMandateService,
to avoid further calls to GoCardless and persisting data locall
- Moved state transition before updating mandate to avoid
having updated the mandate, but could not transition state
- Split confirmedDirectDebitDetailsFor into two separate methods, specific
for each mandate type. These method was called from specific mandate service
so we knew beforehand what functionality we want.
- This brings more clarity in what the next action should be from each
specific mandate service

PP-3986 - Move state check first

---

src/main/resources/migrations/00039_alter_table_mandates_drop_column_creditor_id.sql
src/main/resources/migrations/00040_alter_table_gocardless_mandates_add_column_gocardless_creditor_id.sql

Migrate creditor id from `mandates` to `gocardless_mandates`
`creditor_id` is GoCardless specific, so we need to migrate it to `gocardless_mandates`:
- Drop `mandates.creditor_id` (it is still not used)
- Create `gocardless_mandates.gocardless_creditor_id`
with @danworth

PP-4002 Migrate creditor id from `mandates` to `gocardless_mandates`

---

src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateService.java
src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitEvent.java
src/main/java/uk/gov/pay/directdebit/payments/services/DirectDebitEventService.java
src/main/java/uk/gov/pay/directdebit/tokens/resources/SecurityTokensResource.java

- We were recording an `awaiting direct debit details` event which was
erroneously set to `TOKEN_EXCHANGED`.
The awaiting direct debit details gives us no extra info, because it
does happen straight after the token exchanged, so we might as well
remove it.

PP-3835 Remove extra TOKEN_EXCHANGED event

---

src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateService.java
src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitEvent.java
src/main/java/uk/gov/pay/directdebit/payments/services/DirectDebitEventService.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/DirectDebitEventServiceTest.java

- We should record an event when we create and store
a mandate in our DB. Otherwise, for example, on demand
mandates will have 0 events until the token exchange

PP-3835 Add MANDATE_CREATED event

---

src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java
src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacade.java
src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactory.java
src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientWrapper.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java
src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacadeTest.java
src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactoryTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java

- GoCardless client related classes `GoCardlessClientWrapper`, `GoCardlessClientFactory`, `GoCardlessClientFacade` belong to `common` package as they can be used outside of `payments` package

PP-4002 Move GoCardless client related classes to "common" package

---

src/main/resources/migrations/00041_alter_table_gocardless_mandates_set_gocardless_creditor_id_not_null.sql

- Initialise `gocardless_mandates.gocardless_creditor_id` with default value `LEGACY_CREDITOR_ID` to make new mandates correct until all changes complete.
- Update `gocardless_mandates.gocardless_creditor_id` with value `LEGACY_CREDITOR_ID` to make existing mandates correct until all changes complete.
- Add `NOT NULL` constraint
with @danworth

PP-4002 Make `gocardless_mandates.gocardless_creditor_id` not null

---

src/main/resources/migrations/00042_alter_table_gocardless_mandates_drop_gocardless_creditor_id_default.sql

Drop `DEFAULT` from `gocardless_mandates.gocardless_creditor_id`
Part of https://github.com/alphagov/pay-direct-debit-connector/pull/248 clean up
with @danworth

PP-4002 Drop `DEFAULT` from `gocardless_mandates.gocardless_creditor_id`

---

src/main/resources/migrations/00043_create_table_oauth_states.sql

- Added a table that will hold state values used to send to GoCardless
- The state value is returned to us from GoCardless and we will use it
to check if is valid against a gateway account external id
- check if migration run successfully

PP-4043 Link GoCardless account to GOV.UK Pay account

---

src/main/java/uk/gov/pay/directdebit/common/services/SunService.java
src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/SunServiceTest.java
src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/TransactionResourceIT.java
src/test/java/uk/gov/pay/directdebit/util/GoCardlessStubs.java
src/test/java/uk/gov/pay/directdebit/util/TestRequestResponsesLoader.java
src/test/resources/it/responses/gocardless/get-creditor-with-bacs-success.json

Use real SunName instead of placeholder when sending emails.
- Created SunService to expose getSunNameFor().
- Get SunName when sending created mandate and confirm transaction emails rather than using the default `THE-CAKE-IS-A-LIE`.
- Added WireMock for GoCardless GET creditor.
- Added tests as appropriate.
with @DanailMinchev

PP-4002 Use real SunName instead of placeholder when sending emails.

---

src/main/resources/migrations/00044_add_return_uri_table_gocardless_partner_app_account_connect_tokens.sql

- When making a GET or POST request to GoCardless Connect we need to send
a `return_uri` in our requests. This `return_uri` is initially added to the
configuration when setting up the Partner app on the GoCardless portal.
Now will be stored against the token, as it will be known by `selfservice`
at the time when the first GET request will be made to GoCardless Connect.
We use it in `dd-connector` just for the POST payload and GoCardless should
respond to the POST request and not to the `return_uri` sent in the payload.
Adding this parameter to the payload seems to be only an extra safety check.

PP-4043 Add column return_uri

---

src/main/java/uk/gov/pay/directdebit/app/config/GoCardlessAppConnectConfig.java

Added Proxy config to the GoCardlessAppConnectClient so it can talk to the outside world using our
proxy, otherwise cannot .

PP-4043 Add Proxy to talk to GoCardless

---

src/test/java/uk/gov/pay/directdebit/junit/DropwizardAppWithPostgresRule.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java

Because we need to run the contract tests multiple times (using pacts tagged
with 'master', 'test', 'staging' and 'production') we need to refresh the
database by deleting data.
@oswaldquek

PP-4082: Refresh database

---

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java

Taking out the PACT_CONSUMER_TAG before meant that the pay-direct-debit-connector provider
tests running in the consumer (e.g. pay-publicapi) PR builds wasn't using the
consumer pact tagged with its branch name.
@oswaldquek

bau: Reinstate PACT_CONSUMER_TAG

---

pom.xml

Upgrade GoCardless SDK from `3.7.0` to `3.7.1`

PP-3776 Upgrade GoCardless SDK

---

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacade.java
src/main/java/uk/gov/pay/directdebit/healthcheck/resources/HealthCheckResource.java

- `networkaddress.cache.ttl` is a setting specified in `java.security` to indicate the caching policy for successful name lookups from the name service.
The default behavior is to cache forever when a security manager is installed, and to cache for an implementation specific period of time, when a security manager is not installed.
- we want to change DNS name lookups cache timeout to be very short, because our proxy's dns needs to be accurate, especially when making reguests to GoCardless
More information:
- https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-jvm-ttl.html
- https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html

PP-4197 Enable "networkaddress cache ttl" setting

---

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactory.java
src/main/java/uk/gov/pay/directdebit/common/proxy/CustomInetSocketAddressProxySelector.java
src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactoryTest.java

This PR adds custom `ProxySelector` to create a new proxy instance each time because egress load balancer IP address can change and we invoke old/invalid IP addresses when using GoCardless OkHttp client.
Please see commits for more information.

PP-4197 Custom ProxySelector

---

pom.xml

Reverts alphagov/pay-direct-debit-connector#288
This was causing some build breakage. Will investigate properly after other dependency updates.

Revert "Bump pact-jvm-provider-junit_2.12 from 3.5.18 to 3.5.24"

---

pom.xml

Reverts alphagov/pay-direct-debit-connector#294
Builds currently failing with `ERROR:  relation "public.databasechangeloglock" does not exist`. Let's revert this for now and get the other dependency upgrades done

Revert "Bump org.eclipse.persistence.jpa from 2.6.4 to 2.7.3"

---

pom.xml

Direct Debit connector does not currently use EclipseLink so this dependency can be removed

Remove EclipseLink JPA 2.6.4 from Maven POM

---

pom.xml

Some of our Pact tests seem to need this. It appears we were relying on getting this via EclipseLink previously.

Add dependency on GlassFish JSON processing default provider 1.1.3

---

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactory.java
src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactoryTest.java

This is small improvement to replace ProxySelector with InetSocketAddress.createUnresolved.
Currently we use custom ProxySelector ( https://github.com/alphagov/pay-direct-debit-connector/blob/6f423b5dddddf2039aa1f878c4865eefe2e226ae/src/main/java/uk/gov/pay/directdebit/common/proxy/CustomInetSocketAddressProxySelector.java ) which is used as a default proxy selector for any outbound Java requests https://github.com/alphagov/pay-direct-debit-connector/blob/6f423b5dddddf2039aa1f878c4865eefe2e226ae/src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java#L93
We want to change the configuration and implementation and not to use custom ProxySelector when initialising GoCardless SDK
We should use `InetSocketAddress.createUnresolved(configuration.getProxyConfig().getHost(), …

PP-4268 Use InetSocketAddress.createUnresolved instead of setting default ProxySelector

---

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java

The upgrade of pact (https://github.com/alphagov/pay-direct-debit-connector/pull/311) has pulled in this change:
https://github.com/DiUS/pact-jvm/commit/65cd756497fd3f2161d00830c594fd37520d5ab5
which causes connection failures to our pact broker.
Specifying 'protocol' is now deprecated, so we should use 'scheme' instead and
let the port be inferred

BAU: Switch to specifying scheme instead of protocol & port for pact

---

pom.xml

This reverts commit bf939bd9e3e56a1ae30286371cdbef0736cbd858.
It looks like upgrading pact stops us from publishing pacts. Revert this until
we can figure out what's going on.

Revert "Bump pact-jvm-provider-junit_2.12 from 3.5.24 to 3.6.0"

---

src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/common/proxy/CustomInetSocketAddressProxySelector.java

- Add `CustomInetSocketAddressProxySelector` which sets proxy for all
outbound HTTPS requests and uses new system properties introduced in
#333
- `CustomInetSocketAddressProxySelector` will be used with GoCardless SDK
when there is no explicit proxy setting on the SDK client

PP-4584 Use custom proxy selector for outbound HTTPS requests

---

src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResponse.java
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResultResponse.java

Simplify object identity methods in `PaymentViewResponse` and `PaymentViewResultResponse` using `Objects.equals()`, `Objects.hash()` and `String.format()`.
In the process, I discovered a bug in `PaymentViewResultResponse.equals()` (see individual commits fot details)

Simplify object identity methods

---

docker-startup.sh

We can't modify the default Java truststore at the moment because we mount a
readonly volume over the top of it.
Until we can remove that volume, make a working copy of the truststore and
modify that instead.

PP-4864: Work on a writeable copy of the default Java truststore

---

docker-startup.sh
src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java
src/main/java/uk/gov/pay/directdebit/app/ssl/TrustStoreLoader.java
src/main/java/uk/gov/pay/directdebit/app/ssl/TrustingSSLSocketFactory.java
src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactory.java
src/main/java/uk/gov/pay/directdebit/notifications/clients/ClientFactory.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactoryTest.java

Revert changes to truststore handling.
It takes too long to build this truststore - revert these changes until we can
come up with a better way.
Revert 4133711771b9d32757c11e5e586daf4c6babd71a and
7c3d98363ef2581bb91601408d4f3baca2530923
This takes the codebase back to `alpha_production-2-243`

PP-4864: Back out changes

---

build-local.sh
pom.xml
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java
src/test/java/uk/gov/pay/directdebit/events/resources/GetDirectDebitEventsIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceIT.java
src/test/java/uk/gov/pay/directdebit/tasks/resources/ExpireResourceIT.java

Named all integration tests consistently, to match the default patterns for the surefire and failsafe maven plugins.
Removed duplication in the pom for the surefire version using a property.
Included unit tests in `build-local.sh`
`mvn test` should only run unit tests, as should `./build-local.sh`
`mvn verify` should run all tests, first unit tests, then package the .jar and then finally run integration tests.
I'm not wholly convinced our integration tests meet the failsafe plugin's definition of what it expects an integration test to be, but they are a bit more bulky than unit tests have a right to be.
See the surefire documentation for the default inclusion pattern: https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html
and the corresponding failsafe …

Cleanup test structure

---

src/test/java/uk/gov/pay/directdebit/events/resources/GetDirectDebitEventsIT.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceIT.java

In preparation for Java 11 fix the format of the expected date strings to
millisecond precision as per the agreed precision from our end-points.
CI will ensure that this change is compatible with existing Java 8. If you wish to test that this addresses the date precision issue introduced with Java 11, then please....
set `JAVA_HOME` to point to an 11 JDK. Verify that Maven is using an 11 JDK with `mvn -version` and you should see something similar to:
```
gds5062:pay-direct-debit-connector danworth$ mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T19:49:05Z)
Maven home: /Users/danworth/Applications/apache-maven-3.5.3
Java version: 11, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home
Default locale: en_GB, …
```

PP-4951 Fix date time precision in tests.

---

Dockerfile

Upgrade to our OpenJDK base image based on Alpine 3.9 with OpenJDK 8u201

PP-4985: Upgrade Alpine & Java

---

Dockerfile
Jenkinsfile
docker-startup.sh
pom.xml

- Set `JAVA_HOME` to the 11 JDK for building on CI.
- Replace `source` and `target` with new `release` flag and set it to `11`.
- Change base image to our new 11 JRE based upon AdoptOpenJDK image `openjdk:adoptopenjdk-jre-11.0.2.9-alpine`
These changes will upgrade DDConnector to Java 11.

PP-5020 Migrate to Java 11

---

src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java

Upgrading Drop Wizard to 1.3.9 upgrades JDBI which will not permit cols of the same name being returned in the same result set (appears to be related to how it uses reflection). This fixes the issue so that we can upgrade.
- Correct `DatabaseTestHelper.getTokenByMandateExternalId` and `getTrasnactionsForMandate`
to return only contents of `tokens` and `transactions` table respectively. New version of JDBI appears to use reflection which complains if two cols in the same result set have the same name
which makes sense since the returned map cannot know which of the multiple keys to
have used. This occurs on multiple fields if joining transactions and mandates tables.
- Correct the assertion to test the status of the transaction which should be
PENDING and not the mandate state which is …

Correct tests to enable DropWizard upgrade

---

src/test/java/uk/gov/pay/directdebit/payments/resources/TransactionResourceIT.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java

I found another test that needs correcting for Dropwizard upgrade.
Drop Wizard 1.3.9 upgrades JDBI which will not permit same named col in the same
result set (this makes sense since the resulting `Map<String, Object>` will not
know which key to use and this causes confusion/unexpected results). This
changes `DatabaseTestHelper.getMandateByTransactionExternalId` to only return the
mandate details and avoid conflicting cols of `id` and `external_id`.

BAU Fix tests to enable upgrade to Drop Wizard 1.3.9

---

src/main/java/uk/gov/pay/directdebit/common/util/URIBuilder.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/GatewayAccountParamConverterProvider.java

This means that a build has no warnings generated by the Java code itself.

Eliminate last couple of compiler warnings in code

---

src/main/java/uk/gov/pay/directdebit/common/exception/BadRequestExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/common/exception/InternalServerErrorExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/common/exception/JsonMappingExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/common/exception/NotFoundExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/common/exception/PreconditionFailedExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/common/model/ErrorIdentifier.java
src/main/java/uk/gov/pay/directdebit/common/model/ErrorResponse.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/payers/resources/PayerResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/TransactionResourceIT.java

- Make it so that all error responses include a "message" field, the value of which is an array of strings and and "error_identifier" field.
- For now, the "error_identifier" is always GENERIC.
- The ErrorIdentifier enum has been created here for now, but will be moved to pay-java-commons.

PP-5142 Include error_identifier in error responses

---

src/main/java/uk/gov/pay/directdebit/common/exception/PreconditionFailedException.java
src/main/java/uk/gov/pay/directdebit/common/exception/PreconditionFailedExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/common/model/ErrorIdentifier.java
src/main/java/uk/gov/pay/directdebit/payments/exception/InvalidMandateTypeException.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/TransactionResourceIT.java

- Public API handles precondition failed responses from some endpoints by assuming these are because the mandate type is invalid. Add in an error_identifier for these responses so that Public API can be sure of this rather than making assumptions.

PP-5142 Add error_identifier for InvalidMandateTypeException

---

build-local.sh
pom.xml

These parameters were being set to their default values, so we don't need to
set them. See
http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html
Also, correct the maven target for local builds - `verify` is the catch-all maven target so we should use that instead of just `package`. This matches what CI does.

Remove parameters from the maven surefire plugin

---

src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/MandateMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/model/subtype/MandateExternalId.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequest.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/MandateFixture.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
src/test/java/uk/gov/pay/directdebit/payers/services/PayerServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/TransactionResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java

`of(…)` and `valueOf(…)` did the same thing — standardise on `valueOf()` because the default parameter conversion code used by JAX-RS looks for a `valueOf(String)` method and it’s easier to submit to its conventions than to add a `ParamConverter`.

PP-5231 Remove unused methods from MandateExternalId

---

src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/OnDemandMandateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/OneOffMandateService.java
src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitStatesGraph.java
src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/test/java/uk/gov/pay/directdebit/mandate/model/MandateStatesGraphTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/OnDemandMandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/OneOffMandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/model/PaymentStatesGraphTest.java

- Make `DirectDebitStatesGraph` return Optional<State> rather than throwing an
exception if no next state can be found. This exception was being relied upon
to control logic with confusing methods such as `void canUpdateStateFor` which
appears to be asking a question but with a return type of `void` was relying upon
the exception being thrown deeper down.
- Move the throwing of exception higher in the call stack and in the context of
the check that was being performed. e.g canUpdateState() ? do something : throw exception.

PP-5232 Remove reliance on exception to control logic

---

src/main/java/uk/gov/pay/directdebit/mandate/services/OnDemandMandateService.java
src/main/java/uk/gov/pay/directdebit/payments/resources/TransactionResource.java
src/main/java/uk/gov/pay/directdebit/payments/services/TransactionService.java
src/test/java/uk/gov/pay/directdebit/mandate/services/OnDemandMandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/TransactionServiceTest.java

- The collect method belongs in the TransactionService as it returns a Transaction
and deals primarily with TransactionService methods.
- This removes a key difference between the OnDemandMandateService and
the OneOffMandateService and will help to bring these two classes together, they
now contain only two methods of the same name.
- Transfer test of collect method to TransactionServiceTest.
- Rename collect method to createOnDemandTransaction to align with naming
convention within TransactionService and be more descriptive.

PP-5232 Remove collect method from OnDemandMandateService

---

src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacade.java
src/main/java/uk/gov/pay/directdebit/common/model/subtype/gocardless/creditor/GoCardlessCreditorId.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/GoCardlessMandateMapper.java
src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacadeTest.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/GoCardlessMandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/GoCardlessMandateFixture.java
src/test/java/uk/gov/pay/directdebit/payments/dao/GoCardlessDirectDebitDirectDebitEventDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java

`of(…)` and `valueOf(…)` did the same thing — standardise on `valueOf()` because the default parameter conversion code used by JAX-RS looks for a `valueOf(String)` method and it’s easier to submit to its conventions than to add a `ParamConverter`.

PP-5231 Rationalise methods in GoCardlessCreditorId

---

src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacade.java
src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientWrapper.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/GoCardlessMandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/GoCardlessMandateMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/model/GoCardlessMandate.java
src/main/java/uk/gov/pay/directdebit/mandate/model/GoCardlessMandateId.java
src/main/java/uk/gov/pay/directdebit/mandate/model/GoCardlessMandateIdArgumentFactory.java
src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessEventService.java
src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacadeTest.java
src/test/java/uk/gov/pay/directdebit/junit/TestContext.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/GoCardlessMandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/GoCardlessMandateFixture.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessEventServiceTest.java
src/test/java/uk/gov/pay/directdebit/util/GoCardlessStubs.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceIT.java

`GoCardlessMandateId` represents the ID GoCardless assign to a Direct Debit mandate. It wraps a string like `"MD123"`.

PP-5231 Introduce GoCardlessMandateId type

---

src/main/java/uk/gov/pay/directdebit/notifications/clients/ClientFactory.java

Use proxy properties set on the JVM to configure the proxy for a Jersey Client. This fixes sending requests to GoCardless.
Copied how it is configured in our other microservices.
Already tested this on test-12 and it fixes the problem.

PP-5193 Configure proxy for Jersey client

---

src/main/resources/migrations/00045_alter_table_gateway_account.sql

The service name was removed in the call to dd-connector at
https://github.com/alphagov/pay-selfservice/pull/1482.
Before I remove the service name from GatewayAccountResponse and
CreateGatewayAccountRequest the service_name column in the gateway_accounts
table needs to be made nullable.
Once I remove the service name from GatewayAccountResponse and
CreateGatewayAccountRequest in another PR I'll be delete to drop the column
completely.

PP-5234: Make service name nullable

---

src/test/java/uk/gov/pay/directdebit/mandate/fixtures/MandateFixture.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java

- There is not currently a pact test with Public API for the collect payment endpoint. Modify the setup of the state so that the test will work then it is added.

PP-5242 Fix pact state for collect payment tests

---

src/main/java/uk/gov/pay/directdebit/mandate/api/CreateMandateRequest.java
src/main/java/uk/gov/pay/directdebit/mandate/api/CreateMandateRequestValidator.java

Make agreement_type field in the create mandate request optional and default to ON_DEMAND so that it can be removed from consuming applications.
PP-5243 will remove mandate/agreement types entirely.

PP-5242 Make mandate type optional

---

src/main/java/uk/gov/pay/directdebit/gatewayaccounts/api/CreateGatewayAccountRequest.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/api/GatewayAccountResponse.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDao.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/dao/mapper/GatewayAccountMapper.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/model/GatewayAccount.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountService.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/MandateMapper.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/api/CreateGatewayAccountRequestTest.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDaoIT.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResourceIT.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/GatewayAccountFixture.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentViewServiceTest.java

I'm not sure whether to just remove the `@NotEmpty` on CreateGatewayAccountRequest's `serviceName` field first. Given direct debit connector isn't in production i thought maybe we could remove the `serviceName` field as well. This relates to https://github.com/alphagov/pay-selfservice/commit/422511d1e0cfcb37568b390902a8db7ed6eddc66.

PP-5234: Remove references to service name

---

src/main/resources/migrations/00049_alter_table_gocardless_mandates.sql

This is a precusor to dropping the column

PP-5245: Make gocardless_creditor_id not null

---

src/main/resources/migrations/00052_alter_table_mandates_add_payment_provider_id.sql

- This id represents the id used by the payment provider (e.g. Gocardless)
to identify the mandate.

PP-5246 Add payment_provider_id to mandates table

---

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/MandateMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/model/GoCardlessMandateId.java
src/main/java/uk/gov/pay/directdebit/mandate/model/Mandate.java
src/main/java/uk/gov/pay/directdebit/mandate/model/PaymentProviderMandateId.java
src/main/java/uk/gov/pay/directdebit/mandate/model/SandboxMandateId.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/MandateFixture.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java

- Create PaymentProviderMandateId abstract class
- Make GoCardlessMandateId and SandboxMandateId extend PaymentProviderMandateId
- add paymentProviderId to Mandate typed as PaymentProviderMandateId.
- add MandateBuilder to avoid overloaded constructor with many arguments.
- amend SQL to store and retrieve payment_provider_id
- amend tests to ensure correct read/write of payment_provider_id.

PP-5246 Add PaymentProviderId to mandates

---

pom.xml
src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactory.java
src/main/java/uk/gov/pay/directdebit/common/exception/NoAccessTokenException.java
src/main/java/uk/gov/pay/directdebit/common/exception/NoAccessTokenExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/common/exception/UnlinkedGCMerchantAccountException.java
src/main/java/uk/gov/pay/directdebit/common/exception/UnlinkedGCMerchantAccountExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/config/GoCardlessFactory.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactoryTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/resources/config/test-it-config.yaml

- Introduces new exceptions to be thrown if a mandate is created by a user who does not have a linked GoCardless account
- Removes access token from config files to ensure that access token is never used as a fallback

PP-5278 Don't allow mandate creation if GoCardless account isn't linked

---

src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacade.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/GoCardlessMandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/MandateMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/model/Mandate.java
src/main/java/uk/gov/pay/directdebit/mandate/model/PaymentProviderMandateIdAndBankReference.java
src/main/java/uk/gov/pay/directdebit/mandate/model/PaymentProviderMandateIdArgumentFactory.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateQueryService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java
src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/TransactionMapper.java
src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitPaymentProviderCommandService.java
src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java
src/main/java/uk/gov/pay/directdebit/tokens/api/TokenResponse.java
src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacadeTest.java
src/test/java/uk/gov/pay/directdebit/junit/TestContext.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/GoCardlessMandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/MandateFixture.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateServiceTest.java
src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceOnDemandTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java

No longer persist GoCardlessMandate when confirming a mandate and prepare for
deletion of GoCardlessMandate class, service and Dao. Includes:
- Rename Mandate field mandateReference to mandateBankStatementReference to help
clarify between the other serviceReference field.
- No longer persist the gocardlessMandate after creation with GoCardless.
- No longer create a GoCardlessMandate within the GoCardlessClientFacade, instead
return a new PaymentProviderConfirmMandateResponse which includes the GoCardless
mandate Id and the bank statement reference.
Update:
@alexbishop1 I have introduced a `PaymentProviderConfirmMandateResponse` to avoid mutating a `Mandate` object within the lower level GoCardless/Sandbox services. I think this makes it clearer and leaves the logic to mutate the Mandate …

PP-5246 No longer persist GoCardlessMandate

---

src/main/resources/migrations/00053_drop_gocardless_mandates_table.sql
src/main/resources/migrations/00054_alter_table_mandates_add_payment_provider_id_index.sql

- Drop `gocardless_mandates` table
- Add index for `payment_provider_id` to the `mandates` table

PP-5246 Drop gocardless_mandates table

---

src/main/java/uk/gov/pay/directdebit/events/dao/SandboxEventDao.java
src/main/java/uk/gov/pay/directdebit/events/dao/SandboxEventMapper.java
src/main/java/uk/gov/pay/directdebit/events/model/SandboxEvent.java
src/main/java/uk/gov/pay/directdebit/events/services/SandboxEventService.java
src/main/java/uk/gov/pay/directdebit/mandate/model/SandboxMandateIdArgumentFactory.java
src/main/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResource.java
src/test/java/uk/gov/pay/directdebit/events/dao/SandboxEventDaoIT.java

PP-5246 Use SandboxMandateId within SandboxEvent
- Change `mandateId` type from `String` to `SandboxMandateId`
- Make return type of getPaymentId and getMandateId optional
with @RoryMalcolm

PP-5246 Use SandboxMandateId within SandboxEvent

---

src/main/resources/migrations/00055_create_table_payments.sql

- This will replace the transactions table.
Same as the transaction table with addition payment_provider_id and charge_date columns. In the next PRs I will switch TransactionsDao to use this table (renaming it to PaymentsDao) then drop the transactions table.

PP-5248 Create payments table

---

src/main/java/uk/gov/pay/directdebit/events/api/DirectDebitEventExternalView.java
src/main/java/uk/gov/pay/directdebit/events/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/directdebit/mandate/api/CreateMandateRequest.java
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResultResponse.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResource.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
src/test/java/uk/gov/pay/directdebit/pact/SelfServiceApiContractTest.java

Pact tests were disabled whilst changing `transaction` to `payment` which impacted
aspects of the API. Now that the changes have been made in PublicApi the Pact tests
are being re-enabled.
Might need some coordination with other changes so please don't merge.

PP-5248 Re-enable pact tests

---

src/main/java/uk/gov/pay/directdebit/events/api/DirectDebitEventExternalView.java
src/main/java/uk/gov/pay/directdebit/events/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/directdebit/mandate/api/CreateMandateRequest.java
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResultResponse.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResource.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java

- This reverts commit f32f1db96f31fb14ae8d0ef76cb7892ba93135b7.
- This reverts commit da9fc1aaf449ae845e9a647a3628a7a62469fa48.
- This reverts commit 9447edd9e8738abf8d10579adabecdf2abee6844.
- This reverts commit abc577693f4acdfbbd48eddb6f93e57599c254db.
In order to make pact tests work after being disabled we temporarily added some transaction API elements back. Now that Pacts are enabled and passing we are reverting those changes which should conclude the work to change `transaction` to `payment`.

PP-5248 Revert temporary transaction API readditions

---

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java
src/main/java/uk/gov/pay/directdebit/payments/model/Payment.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java

-  Adds logic to return the provider ID and mandate ID in the
response object upon the creation of a payment
-  Currently does not return provider ID but will do so when
the provider ID logic is implemented
-  Tests have been updated to ensure that the mandate ID is
correctly returned

PP-5298 Add ProviderID and MandateID to Create Payment response

---

src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentMapper.java
src/main/java/uk/gov/pay/directdebit/payments/model/Payment.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentProviderPaymentIdArgumentFactory.java
src/test/java/uk/gov/pay/directdebit/junit/TestContext.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/PaymentFixture.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceIT.java
src/test/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResourceIT.java

- Add to PaymentDao, PaymentMapper and associated tests and fixtures.
- Includes some renaming of `transaction` to `payment` mostly for test variable names.

PP-5428 Persist and retrieve PaymentProviderPaymentId  on Payment

---

src/main/java/uk/gov/pay/directdebit/mandate/api/DirectDebitInfoFrontendResponse.java
src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java
src/main/java/uk/gov/pay/directdebit/payments/api/ExternalPaymentState.java
src/main/java/uk/gov/pay/directdebit/payments/api/ExternalPaymentStateWithDetails.java
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentResponse.java
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewResultResponse.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentViewService.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/api/PaymentResponseTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentViewServiceTest.java

Include a "details" field in the state object for Payment responses.
This will contain the "details[cause]" obtained from a Go Cardless event.
Currently this is always set to a hardcoded value and needs to be wired
up to an actual value retrieved from the database when event processing
is implemented properly.
Co-authored-by: Rory Malcolm <rory.malcolm@digital.cabinet-office.gov.uk>

PP-5298 Include details for payment state in responses

---

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequest.java
src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequestValidator.java
src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java

- Accept "mandate_id" as well as "agreement_id" for a collect payment
request so that the field can be renamed.
- Return "payment_id" as well as "charge_id" for the response so that
the field can be renamed.

PP-5298 Rename fields for collect payment

---

pom.xml

Pact tests began failing on master after this upgrade was merged.
Reverts alphagov/pay-direct-debit-connector#509

Revert "Bump pact-jvm-provider-junit_2.12 from 3.6.7 to 3.6.8"

---

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java
src/main/java/uk/gov/pay/directdebit/payments/model/Payment.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentDaoIT.java

Make the `Payment.getPaymentProviderPaymentId()` method on `Payment` return an `Optional<PaymentProviderPaymentId>` because there may not always be one.

PP-5248 Payment.getPaymentProviderPaymentId(): return Optional

---

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequestValidator.java
src/test/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequestValidatorTest.java

Disabled validation for the agreement_id field on a collect payment
request so that the renamed mandate_id field can be used

PP-5298 Disable validation for agreement id

---

src/main/java/uk/gov/pay/directdebit/payments/api/ExternalPaymentState.java
src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentViewResourceIT.java

- Check returned state when collecting payments within PaymentResourceIT
- Fix ExternalPaymentState to avoid returning erroneous and superfluous 'state'
element.

PP-5428 Add tests for state in PaymentResourceIT

---

src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentMapper.java
src/main/java/uk/gov/pay/directdebit/payments/model/Payment.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentResource.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java
src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/PaymentFixture.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java

Make Payment immutable — modifications are now performed by taking
a copy and using a builder.
Some unused and forgotten one-off payment functionality removed.

PP-5248 Make Payment immutable and use builder-based instantiation

---

src/main/java/uk/gov/pay/directdebit/mandate/model/Mandate.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateService.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateServiceTest.java

For consistency with `Payment` which has been made immutable this makes `Mandate`
immutable. Modifications are now performed by taking a copy and using a builder.

PP-5248 Make Mandate Immutable

---

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequest.java
src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequestValidator.java
src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java
src/test/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequestValidatorTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java

Remove allowing request to contain "agreement_id", now requires "mandate_id".
Remove "charge_id" field from response, now "payment_id" is used.

PP-5298 Remove old fields for collect payment request

---

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/exception/MandateNotFoundException.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateQueryService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java
src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java
src/main/java/uk/gov/pay/directdebit/payments/model/DirectDebitPaymentProviderCommandService.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentResource.java
src/main/java/uk/gov/pay/directdebit/payments/services/CollectService.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java
src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/PaymentFixture.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/CollectServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java

This allows us to set the `PaymentProviderId` and `ChargeDate` for all services at a common point for all providers within `PaymentService`. This means that we now persist the provider ID and charge date for sandbox as well as GoCardless (the values are arbitrary for sandbox).
As part of this, untangle creating a payment from collecting a payment in `PaymentService` by introducing a new `CollectService` to orchestrate the overall operation.
This code may be easier to understand by reviewing the individual commits.
with @danworth

PP-5248 Return provider ID and charge date from provider service

---

src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java
src/main/java/uk/gov/pay/directdebit/mandate/resources/MandateResource.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/payers/dao/PayerDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentViewMapper.java
src/main/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResource.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
src/test/java/uk/gov/pay/directdebit/payers/dao/PayerDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java

Rename “transaction” to “payment” except in `DirectDebitEvent` and friends because that’s going away soon.

PP-5318 s/transaction/payment/g

---

src/main/java/uk/gov/pay/directdebit/common/json/ToLowerCaseStringSerializer.java
src/main/java/uk/gov/pay/directdebit/mandate/api/CreateMandateResponse.java
src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentResponse.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java

Add a ToLowerCaseStringSerializer to serialize a value to a lower case string. Use this in the payment and mandate response models along with the PaymentProvider enum type on the field.

PP-5298 Return payment_provider as lower case

---

src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java
src/main/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDao.java
src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessEventService.java
src/test/java/uk/gov/pay/directdebit/payments/dao/GoCardlessDirectDebitDirectDebitEventDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessEventServiceTest.java

Move `GoCardlessEventDao` from `uk.gov.pay.directdebit.payments.dao` to `uk.gov.pay.directdebit.events.dao`.

PP-5318 Move GoCardlessEventDao to correct package

---

src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java
src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java

This used to be generated on creation of the mandate but it is more appropriate
to generate it on the confirmation as that mimicks what a real direct debit
payment provider would do.

PP-5299: Generate mandate bank ref on sandbox confirmation

---

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java

Set a state that is not "created" for the provider state "a gateway account
with external id and a confirmed mandate exists".
This fixes https://github.com/alphagov/pay-publicapi/pull/568

PP-5299: Fix contract test

---

pom.xml
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/model/GoCardlessOrganisationId.java
src/main/java/uk/gov/pay/directdebit/mandate/model/MandateBankStatementReference.java
src/main/java/uk/gov/pay/directdebit/mandate/model/PaymentProviderMandateId.java
src/main/java/uk/gov/pay/directdebit/mandate/model/subtype/MandateExternalId.java
src/main/java/uk/gov/pay/directdebit/payers/model/AccountNumber.java
src/main/java/uk/gov/pay/directdebit/payers/model/SortCode.java
src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessEventId.java
src/main/java/uk/gov/pay/directdebit/payments/model/PaymentProviderPaymentId.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java

Make specific types that wrap strings extend `WrappedStringValue` so we don’t have identical implementations of `equals(…)`, `hashCode()` etc.
This change also makes `PaymentProviderMandateId` and `PaymentProviderSandboxId` stricter when it comes to equality: `SandboxMandateId.valueOf("foo")` and `GoCardlessMandateId.valueOf("foo")` will no longer be considered to be equal (which is what we want because they’re not). Fix a test that relied on the buggy behaviour.
This may change the hash codes of some objects but since they’re not shared between application nodes or persisted across application restarts, this is fine.

PP-5318 Use WrappedStringValue where appropriate: code reuse FTW

---

src/main/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDao.java
src/main/java/uk/gov/pay/directdebit/events/dao/mapper/GoCardlessEventMapper.java
src/main/java/uk/gov/pay/directdebit/events/model/GoCardlessOrganisationIdArgumentFactory.java
src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessEvent.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParser.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java
src/test/java/uk/gov/pay/directdebit/payments/dao/GoCardlessDirectDebitDirectDebitEventDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/GoCardlessEventFixture.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParserTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessMandateHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java

`GoCardlessEvent` had two fields for the organisation identifier (`"links"."organisation"` in the JSON): `organisationIdentifier` and `linksOrganisation`. The former was a `GoCardlessOrganisationId` while the latter was a `String`. While we parsed both out of the incoming webhook event JSON, only `linksOrganisation` got persisted to and read from the database. In other places, we were inconsistent about which one we used.
Standardise on `linksOrganisation` (for consistency with similar fields in `GoCardlessEvent`) but make the type a `GoCardlessOrganisationId` rather than a `String`.
Remove code that tries to account for events that don’t have an organisation ID: all incoming events should do have an organisation ID (because they’re from an accounts linked to our partner app): there might …

PP-5371 Rationalise organisation identifier in GoCardlessEvent

---

pom.xml
src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/common/exception/GoCardlessAccountAlreadyConnectedException.java
src/main/java/uk/gov/pay/directdebit/common/exception/GoCardlessAccountAlreadyConnectedExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDao.java
src/main/java/uk/gov/pay/directdebit/partnerapp/services/GoCardlessAppConnectAccountService.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDaoIT.java
src/test/java/uk/gov/pay/directdebit/partnerapp/services/GoCardlessAppConnectAccountServiceTest.java

Return a 400 response when we try to exchange a Go Cardless access code
for an access token and the organisation ID in the response is already
stored for a different account.

PP-5334 Return an error when Go Cardless account already linked

---

src/main/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDao.java
src/main/java/uk/gov/pay/directdebit/events/dao/mapper/GoCardlessEventMapper.java
src/main/java/uk/gov/pay/directdebit/events/exception/GoCardlessEventHasNoMandateIdException.java
src/main/java/uk/gov/pay/directdebit/events/exception/GoCardlessEventHasNoPaymentIdException.java
src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessEvent.java
src/main/java/uk/gov/pay/directdebit/payments/services/GoCardlessEventService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java
src/test/java/uk/gov/pay/directdebit/payments/dao/GoCardlessDirectDebitDirectDebitEventDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/GoCardlessEventFixture.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParserTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessMandateHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessHandlerTest.java

- Stop inserting a new `GoCardlessEvent` to the `gocardless_events` table with `GoCardlessEvent.eventId` as the value for the `internal_event_id` column because it will always be null
- Map the` internal_event_id column` (not `event_id`) to `GoCardlessEvent.eventId`
- Map the `event_id` column (not the non-existent `gocardless_event_id`) to `GoCardlessEvent.goCardlessEventId`
- In `GoCardlessEvent`, rename `eventId` to `internalEventId` to match the column name in the `gocardless_events` database table because the table also has an `eventId` column (which maps to `goCardlessEventId`) and it’s confusing
This is almost certainly easier to review commit by commit.

PP-5318 Fix GoCardlessEvent persistence and depersistence

---

src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java
src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java

Testing of story PP-5300 showed that the provider_id wasn't present when getting a sandbox direct debit payment. This PR fixes it.

PP-5300: Update sandbox payment with provider id and charge date

---

pom.xml
src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/common/exception/MandateStateInvalidExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/exception/MandateStateInvalidException.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentResource.java
src/main/java/uk/gov/pay/directdebit/payments/services/CollectService.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java
src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/CollectServiceTest.java

- If a mandate has an invalid state and cannot take payments, currently the payment is accepted then an error occurs further down the line of the user journey.
- This fix changes that and does not allow payments to be created if a mandate has an invalid state, instead an error is returned from DD connector which will be handled in publicapi.

PP-5377 Disallow Payment Creation on Invalid Mandate State

---

src/main/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDao.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculator.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateUpdater.java
src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessMandateIdAndOrganisationId.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/test/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDaoITest.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculatorTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateUpdaterTest.java
src/test/java/uk/gov/pay/directdebit/util/DatabaseTestHelper.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java

After receiving a webhook from GoCardless, update the state of each affected mandate by examining all of the events stored for that mandate, rather than the one that’s just been received. This means that we can handle webhook events from GoCardless for mandates being received out of order.

PP-5318 Update GoCardless mandate state based on all events

---

src/main/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDao.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/model/MandateLookupKey.java
src/main/java/uk/gov/pay/directdebit/mandate/model/PaymentProviderMandateId.java
src/main/java/uk/gov/pay/directdebit/mandate/model/SandboxMandateId.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateUpdateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculator.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateUpdater.java
src/main/java/uk/gov/pay/directdebit/payments/model/GoCardlessMandateIdAndOrganisationId.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/test/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDaoITest.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateUpdateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculatorTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateUpdaterTest.java

GoCardless mandate IDs aren’t unique, so to retrieve a mandate from the database, we have use the mandate ID in combination with the GoCardless organisation ID. Sandbox mandate IDs don’t have this limitation and sandbox accounts don’t have organisation IDs.
Make things simpler for ourselves by introducing a `MandateUpdateService`, which acts as a façade over the `MandateDao` and takes a `MandateLookupKey` object. Both `GoCardlessMandateIdAndOrganisationId` (a value type that wraps a GoCardless mandate ID and organisation ID) and `SandboxMandateId` implement the `MandateLookupKey` marker interface. The
`MandateUpdateService` uses some fantastically non-polymorphic code to determine the precise runtime type of the `MandateLookupKey` it’s been passed and calls the appropriate method on the …

PP-5318 MandateLookupKey for updating mandate state from GC events

---

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java
src/main/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParams.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDaoIT.java

- Adds functionality to direct debit connector relating to searching for mandates including a variety of tests
- Provides functionality to correctly retrieve the total 'count' of the number of mandates that match the inputted search parameters and updates previous existing tests to assert that this is correct.

PP-5302 Add Mandate Search Count Method to DAO

---

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/exception/MandateNotFoundException.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateQueryService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateQueryServiceTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessMandateHandlerTest.java

Conceptually very similar to https://github.com/alphagov/pay-direct-debit-connector/pull/587.
`PaymentProviderServiceId` remains for now as it used for database queries relating to payments.

PP-5318 Use MandateLookupKey for retrieving mandates

---

src/main/java/uk/gov/pay/directdebit/common/model/SearchParams.java
src/main/java/uk/gov/pay/directdebit/common/model/SearchResponse.java
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentViewValidator.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDao.java
src/main/java/uk/gov/pay/directdebit/payments/model/LinksForSearchResult.java
src/main/java/uk/gov/pay/directdebit/payments/params/PaginationParams.java
src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java
src/main/java/uk/gov/pay/directdebit/payments/resources/PaymentSearchResource.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentSearchService.java
src/test/java/uk/gov/pay/directdebit/payments/api/PaymentViewValidatorTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/model/LinksForSearchResultTest.java
src/test/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParamsTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentSearchServiceTest.java

In preparation for using a common interface for `PaymentViewSearchParams` and `MandateSearchParams` the following changes have been made:
- Make fields immutable and introduce a proper builder with static method to create a builder from an existing object.
- Clarify logic within `LinksForSearchResult` to no longer mutate the provided   
`PaymentViewSearchParams` which has confusing side-effects for callers that provided it.
- For consistency with MandateSearchParams and in preparation for a common interface change page and displaySize from Long to Integer.

Pp 5302 Make PaymentViewSearchParams Immutable with Builder

---

src/main/java/uk/gov/pay/directdebit/common/model/SearchParams.java
src/main/java/uk/gov/pay/directdebit/payments/model/LinksForSearchResult.java
src/main/java/uk/gov/pay/directdebit/payments/params/PaymentViewSearchParams.java

To enable re-use of `LinksForSearchResult` introduce a common interface `SearchParams`
which `PaymentViewSearchParams` and in a future commit `MandateSearchParams`
implement.

PP-5302 Introduce common SearchParams interface

---

src/main/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDao.java
src/main/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculator.java
src/test/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDaoITest.java
src/test/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculatorTest.java

Add a calculator that, given a GoCardless payment ID and a GoCardless organisation ID, finds the latest state-changing event that GoCardless sent us for that payment and maps the event’s action to the new payment state.
No actual updating of the state; that will come later.

PP-5431 Add latest GoCardless event to payment state calculator

---

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateUpdateService.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentDao.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentUpdateService.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateUpdateServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentUpdateServiceTest.java

Add a payment status updater that works by querying for stored GoCardless webhook events. It always uses the latest dated (not received/stored) event that has a relevant action and doesn’t enforce any idea of valid state transitions.
Note that this isn’t actually hooked up to anything yet.

PP-5431 Add payment status updater that reads GoCardless events

---

src/main/java/uk/gov/pay/directdebit/app/config/DirectDebitModule.java
src/main/java/uk/gov/pay/directdebit/common/model/SearchParams.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java
src/main/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParams.java
src/main/java/uk/gov/pay/directdebit/mandate/resources/MandateResource.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateQueryService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateSearchService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/payments/model/LinksForSearchResult.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentSearchService.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParamsTest.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceSearchIT.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateSearchResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateQueryServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateSearchServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/model/LinksForSearchResultTest.java

- Remove `GatwayAccountExternalId` from `MandateSearchParams` and `SearchParams` as it
is provided in the URL path and not the search params which means it cannot be added
to MandateSearchParams using `@QueryBean` deserialisation. Instead pass this value
to the necessary service and dao methods.
- Introduce `MandateResourceIT` tests for mandate search

PP-5302 Add logic for mandate search to MandateResource

---

src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java
src/main/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateUpdater.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResource.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateUpdaterTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceIT.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java

After receiving a GoCardless webhook event, update the state of any affected payments by looking at the latest stored event (not just the one that was just received) and calculating the state from the
event’s action. This doesn’t enforce any idea of valid state transitions.
Bypass code that caused us to set all payments as failed if we received an event with a mandate failed action; we should get a separate payment event from GoCardless so this is unnecessary.

PP-5431 Payment status updater that reads GoCardless webhook events

---

src/test/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParamsTest.java

I wrote the test MandateSearchParamsTest.shouldCreateQueryWithAllParams()
which would only ever pass on the 11 July 2019. This fixes the assertion to pass
on any day, please forgive me.

PP-5302 Fix date assertion in test

---

src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java
src/main/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParams.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParamsTest.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceSearchIT.java

Mandate search should work with external states not internal. Note that external
states can map to multiple internal states and we only store the internal state
in the table so conversion is necessary before searching.
As described above. Note the next change will be to permit a list of external states to search on rather than a single value (maybe in another story...)

PP-5302 Change mandate search to use external mandate states

---

src/main/java/uk/gov/pay/directdebit/events/dao/SandboxEventDao.java
src/main/java/uk/gov/pay/directdebit/events/dao/SandboxEventMapper.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java
src/main/java/uk/gov/pay/directdebit/payments/services/sandbox/SandboxPaymentStateCalculator.java
src/main/java/uk/gov/pay/directdebit/payments/services/sandbox/SandboxPaymentStateUpdater.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookSandboxService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessPaymentHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResource.java
src/test/java/uk/gov/pay/directdebit/events/dao/SandboxEventDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/sandbox/SandboxPaymentStateCalculatorTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/sandbox/SandboxPaymentStateUpdaterTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessPaymentHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookSandboxServiceTest.java
src/test/java/uk/gov/pay/directdebit/webhook/sandbox/resources/WebhookSandboxResourceIT.java

After processing a sandbox webhook, update the states of the affected payments (which is really all of them) by examining all stored events rather than the one we just received. No state transition restrictions are enforced.
This brings sandbox into line with GoCardless in terms of its (theoretical) ability to handle out-of-order webhooks.

PP-5432 Read all webhook events when updating sandbox payment state

---

src/main/java/uk/gov/pay/directdebit/common/exception/validation/ExternalMandateStateValidator.java
src/main/java/uk/gov/pay/directdebit/common/exception/validation/ValidExternalMandateState.java
src/main/java/uk/gov/pay/directdebit/mandate/api/ExternalMandateState.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java
src/main/java/uk/gov/pay/directdebit/mandate/model/MandateState.java
src/main/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParams.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParamsTest.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceSearchIT.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceIT.java

- Remove `EXTERNAL` prefix to `ExternalMandateState` values to aid deserialisation.
- Add `ValidExternalMandateState` annotation with validator.
- Add tests for when `state` parameter is an invalid `ExternalMandateState`.
- Modify `MandateSearchDao` to not add `WHERE clause if the list of internal
mandate states is empty since this results in a binding exception. Add test
to assert this.

PP-5302 Validate external state on mandate search

---

src/main/java/uk/gov/pay/directdebit/common/model/DirectDebitStateWithDetails.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateDao.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDao.java
src/main/java/uk/gov/pay/directdebit/mandate/dao/mapper/MandateMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/model/Mandate.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateUpdateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculator.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateUpdater.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/MandateFixture.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateUpdateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculatorTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateUpdaterTest.java

When processing a GoCardless webhook that changes the state of a mandate, store the cause and description if GoCardless supply them.

PP-5442 Update mandate state, cause and description from GC event

---

src/main/java/uk/gov/pay/directdebit/mandate/api/DirectDebitInfoFrontendResponse.java
src/main/java/uk/gov/pay/directdebit/mandate/api/ExternalMandateState.java
src/main/java/uk/gov/pay/directdebit/mandate/api/ExternalMandateStateWithDetails.java
src/main/java/uk/gov/pay/directdebit/mandate/api/MandateResponse.java
src/main/java/uk/gov/pay/directdebit/payments/api/PaymentResponse.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDao.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentMapper.java
src/main/java/uk/gov/pay/directdebit/payments/dao/mapper/PaymentResponseMapper.java
src/test/java/uk/gov/pay/directdebit/mandate/fixtures/MandateFixture.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceSearchIT.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/fixtures/PaymentFixture.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentSearchResourceIT.java

In mandate and payment responses (single and search results), include the `state_details` (granular information about the state provided by the payment provider) as `state.details`.

PP-5442 Expose mandate/payment granular state details in responses

---

src/main/java/uk/gov/pay/directdebit/tasks/services/ExpireService.java
src/test/java/uk/gov/pay/directdebit/tasks/services/ExpireServiceTest.java

This includes CREATED and AWAITING_DIRECT_DEBIT_DETAILS.
This should stop the following in prod. I intend to simplify this process next week (I don't have time today).
```
2019-07-19T14:48:36+00:00 ip6-localhost ecs-production-2_directdebit-connector-249-directdebit-connector-d0c4eebe98b6c1d4f801[1362]: uk.gov.pay.directdebit.events.exception.InvalidGovUkPayEventInsertionException: GOV.UK Pay event MANDATE_EXPIRED_BY_SYSTEM is invalid following event MANDATE_SUBMITTED
```

PP-5354 Only expire mandates before SUBMITTED state

---

src/main/java/uk/gov/pay/directdebit/events/services/GovUkPayEventService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateService.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdater.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateUpdateService.java
src/main/java/uk/gov/pay/directdebit/payers/services/PayerService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/GoCardlessMandateHandler.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdateServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateStateUpdaterTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/MandateUpdateServiceTest.java
src/test/java/uk/gov/pay/directdebit/payers/services/PayerServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GovUkPayEventServiceTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/GoCardlessMandateHandlerTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java

Calculate and update the state of mandate if necessary after inserting a GovUkPayEvent.
No longer store DirectDebitEvents for mandate or use them to update the state.

PP-5358 Update mandate state after inserting GovUkPayEvent

---

src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceIT.java

Update the GoCardless webhook integration tests so they check the `details.cause` of the event is persisted and that it also gets persisted as the `state_details` of the mandate or payment.

PP-5442 Make GoCardless webhook tests check cause becomes details

---

src/main/java/uk/gov/pay/directdebit/events/dao/GovUkPayEventDao.java
src/main/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculator.java
src/test/java/uk/gov/pay/directdebit/events/dao/GovUkPayEventDaoITest.java
src/test/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculatorTest.java

When calculating the state of a GoCardless payment, find the most recent GoCardlessEvent and GovUkPayEvent then use whichever has a later timestamp to calculate the state.

PP-5433 Include GovUkPayEvents in GoCardless payment state calculation

---

src/main/java/uk/gov/pay/directdebit/mandate/services/GovUkPayEventToMandateStateMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessEventToMandateStateMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculator.java
src/main/java/uk/gov/pay/directdebit/mandate/services/sandbox/SandboxMandateStateCalculator.java
src/main/java/uk/gov/pay/directdebit/payments/services/GovUkPayEventToPaymentStateMapper.java
src/main/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessEventToPaymentStateMapper.java
src/main/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculator.java
src/main/java/uk/gov/pay/directdebit/payments/services/sandbox/SandboxEventToPaymentStateMapper.java
src/main/java/uk/gov/pay/directdebit/payments/services/sandbox/SandboxPaymentStateCalculator.java
src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculatorTest.java
src/test/java/uk/gov/pay/directdebit/mandate/services/sandbox/SandboxMandateStateCalculatorTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculatorTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/sandbox/SandboxPaymentStateCalculatorTest.java

When calculating the state of a Sandbox payment, find the most recent Sandbox and GovUkPayEvent then use whichever has a later timestamp to calculate the state.
Add ...EventToPaymentStateMapper classes to share the GovUkPayEvent mapping between the GoCardless and Sandbox calculators. Add classes for GoCardless and Sandbox for consistency, as this was done for the mandate state calculation.

PP-5433 Include GovUkPayEvents in Sandbox payment state calculation

---

src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceMandateActionsIT.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourcePaymentActionsIT.java

In the integration tests, use Dropwizard fixtures to load the files containing GoCardless webhook bodies rather than Guava’s `Resources` (which is still `@Beta`).

PP-5474 Use Dropwizard fixtures to load webhooks in tests

---

src/main/java/uk/gov/pay/directdebit/events/services/GovUkPayEventService.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java
src/test/java/uk/gov/pay/directdebit/payments/services/CollectServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/GovUkPayEventServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java

Recalculate the Payment state and update it if necessary after inserting a GovUkPayEvent. Currently there is only an event for submitted to provider.

PP-5433 Update payment state after inserting a GovUkPayEvent

---

src/main/java/uk/gov/pay/directdebit/tasks/resources/ExpireResource.java
src/main/java/uk/gov/pay/directdebit/tasks/services/ExpireService.java
src/test/java/uk/gov/pay/directdebit/tasks/resources/ExpireResourceIT.java
src/test/java/uk/gov/pay/directdebit/tasks/services/ExpireServiceTest.java

This is a hang-over from one-off payments. Remove code responsible for expiry but keep the expired payments count in the resource response as this may be consumed by the initiating task.

PP-5451 Remove payment expiry

---

src/main/resources/migrations/00062_alter_tables_gocardless_events_mandates_payments_alter_columns_details_description_state_details_description.sql

Change the types of database columns that store `details.description` from GoCardless events from `VARCHAR(255)` to `TEXT` because GoCardless like to be verbose sometimes.
Affected columns are:
• `details_description` in `gocardless_events`
• `state_details_description` in `mandates`
• `state_details_description` in `payments`

PP-5478 Change types of DB columns that hold GoCardless description

---

src/main/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDao.java
src/test/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDaoITest.java

Remove selecting internal_event_id from gocardless_events table so that the column can be dropped.

PP-5451 Remove internal_event_id from select statements

---

src/main/java/uk/gov/pay/directdebit/events/model/GoCardlessResourceType.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java

Add `REFUNDS` and `SUBSCRIPTIONS` to `GoCardlessResourceType` enum. When we receive a webhook event from GoCardless with a `"resource_type"` of `"refunds"` or `"subscriptions"`, we will convert it to a value from the enum before persisting to the database. Without `REFUNDS` and `SUBSCRIPTIONS` in the enum, we were persisting the default `UNHANDLED` (which has now been removed).

PP-5455 Add REFUNDS and SUBSCRIPTIONS to GoCardlessResourceType

---

src/main/java/uk/gov/pay/directdebit/payments/api/CollectPaymentRequestValidator.java

Gocardless have a minimum of 100 pence for payments. This increases the minimum
amount used for validation and brings it inline with PublicApi and GoCardless.

PP-5459 Increase minimum amount for payments to 100 pence

---

src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceMandateActionsIT.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourcePaymentActionsIT.java
src/test/resources/gocardless-webhook-payment-late-failure-settled.json

Add integration test to check that we set the state of a payment to `FAILED` if we receive a webhook from GoCardless with an event with a payment `late_failure_settled` action. Ignored for now until we actually implement this behaviour.
Also enable the test that we set the state of a payment to `PAID_OUT` if we receive a webhook from GoCardless with an event with a payment `paid_out` action because it works now and make some small correctness tweaks to the remaining tests.

PP-5455 Add integration test for GoCardless late_failure_settled

---

src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java
src/main/java/uk/gov/pay/directdebit/payments/model/Payment.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java
src/main/java/uk/gov/pay/directdebit/payments/services/SandboxService.java
src/test/java/uk/gov/pay/directdebit/payments/services/GoCardlessServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/SandboxServiceTest.java

Currently after submitting a payment, we call the DAO to update it both from GoCardlessService and SandboxService. This is different from what we do for a mandate, when the updating is done by the MandateService.
Move this behaviour to PaymentService to make this consistent and remove some duplication.

PP-5451 Move payment updating to PaymentService

---

src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessEventToMandateStateMapper.java
src/test/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessMandateStateCalculatorTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourceMandateActionsIT.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/resources/WebhookGoCardlessResourcePaymentActionsIT.java

When calculating the state of a mandate from received GoCardless events, map the expired action to the expired state.
Enable some GoCardless webhook event integration tests that now pass because of this and related changes.

PP-5455 Map mandate expired GoCardless event to expired state

---

src/main/java/uk/gov/pay/directdebit/mandate/api/ExternalMandateState.java
src/main/java/uk/gov/pay/directdebit/mandate/model/MandateState.java
src/main/java/uk/gov/pay/directdebit/mandate/services/MandateService.java
src/test/java/uk/gov/pay/directdebit/mandate/params/MandateSearchParamsTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/CollectServiceTest.java

Update mandate external states to make it more obvious what they mean and the distinction between states that occurred during user setup and after the mandate has been submitted to the payment provider clearer.

PP-5475 Update mandate external states

---

src/main/java/uk/gov/pay/directdebit/notifications/services/UserNotificationService.java
src/test/java/uk/gov/pay/directdebit/notifications/services/UserNotificationServiceTest.java

- Currently emails sent from notify contain optional objects which are
not unwrapped, when Optional.toString() is called on them this then
displays confusing output to the user, eg Optional[YourSunOutputHere],
to fix this the Optional is now fully unwrapped with Optional.get()
beforehand.

PP-5483 Unwrap Optional in Notify Emails

---

src/main/java/uk/gov/pay/directdebit/mandate/api/ExternalMandateState.java
src/main/java/uk/gov/pay/directdebit/payments/api/ExternalPaymentState.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentSearchResourceIT.java

The "finished" property isn't very useful for direct debits as there aren't really final states, as mandates can be re-activated after they become inactive, and payments can be indemnity claimed. So remove this from the external state objects as it's no longer consumed by Public API.

PP-5475 Remove finished property from state objects

---

src/main/java/uk/gov/pay/directdebit/events/model/GoCardlessEvent.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessEventToMandateStateMapper.java
src/main/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessEventToPaymentStateMapper.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessService.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/SendEmailsForGoCardlessEventsHandler.java
src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/UnhandledGoCardlessEventsLogger.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/WebhookGoCardlessServiceTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/UnhandledGoCardlessEventsLoggerTest.java

Log errors for GoCardless event actions that we've identified as needing operations performed if we receive them, but which we do not expect to receive in standard usage so do not handle.

PP-5455 Log errors for GoCardless events we don't handle

---

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/UnhandledGoCardlessEventsLogger.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/services/handlers/UnhandledGoCardlessEventsLoggerTest.java

2 Commits:
- Add the event id and organisation id in the error message.
- Refactor code slightly.
- Log errors for 'subscriptions' and 'refunds' event resource types as we do not expect to receive these types of events.

PP-5455 Log errors for unhandled GoCardless event resource types

---

src/main/resources/migrations/00065_truncate_tables_sandbox_events_gocardless_events_gocardless_customers_payers_payments_mandates.sql

Delete all rows from the following tables in the following order:
• `sandbox_events`
• `gocardless_events`
• `gocardless_customers`
• `payers`
• `payments`
• `mandates`
We’ve changed the data we store quite substantially with the result that some older data is no longer considered valid. It’s all test data, so we can safely remove it.

PP-5455 Delete data from many Direct Debit connector tables

---

src/main/resources/migrations/00066_truncate_tables_govukpay_events_sandbox_events_gocardless_events_gocardless_customers_payers_payments_mandates.sql

Delete all rows from the following tables in the following order:
• `govukpay_events`
• `sandbox_events`
• `gocardless_events`
• `gocardless_customers`
• `payers`
• `payments`
• `mandates`
We’ve changed the data we store quite substantially with the result that some older data is no longer considered valid. It’s all test data, so we can safely remove it.

PP-5459 Delete data from many Direct Debit connector tables

---

src/main/java/uk/gov/pay/directdebit/payments/api/PaymentResponse.java
src/main/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDao.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentViewDaoIT.java

Previously, we were selecting the mandate payment_provider_id in the DAO. Fix the query to instead select the payment payment_provider_id. Add a test for the DAO to check the extracted response is what we expect.

PP-5517 Return payment provider id in search payments response

---

src/main/resources/config/config.yaml

- Configuration to add environment variables for NonProxyHosts for the
apache client.

PP-5486 Add Extra NonProxyHosts Configuration

---

src/test/java/uk/gov/pay/directdebit/events/dao/GoCardlessEventDaoIT.java
src/test/java/uk/gov/pay/directdebit/events/dao/GovUkPayEventDaoIT.java

This will avoid slow tests being run during 'mvn test'

Use the correct naming scheme for integration tests

---

src/main/java/uk/gov/pay/directdebit/notifications/clients/ClientFactory.java

- Use the SystemRoutePlanner to inject the Environment Variables for
NonProxyHosts into the Jersey Client.

PP-5486 Use SystemRoutePlanner

---

src/main/java/uk/gov/pay/directdebit/common/exception/NotFoundExceptionMapper.java

Many `NotFoundException`s are caused by input that’s outside of our control, so log at WARN (which doesn’t create a support ticket) rather than ERROR (which does).
When we have time, we might want to make any `NotFoundException`s that are not caused by external input log errors again, as this is more indicative of a problem we can do something about.

When processing a NotFoundException, log at WARN rather than ERROR

---

pom.xml

Argh we actually use guava. Just do `git grep -F com.google.common` and you'll see.
Reverts alphagov/pay-direct-debit-connector#729

Revert "bau: we don't actually use guava"

---

src/main/java/uk/gov/pay/directdebit/common/exception/ExceptionSummariser.java
src/main/java/uk/gov/pay/directdebit/common/exception/InternalServerErrorException.java
src/main/java/uk/gov/pay/directdebit/common/exception/InternalServerErrorExceptionMapper.java
src/main/java/uk/gov/pay/directdebit/mandate/services/gocardless/GoCardlessService.java
src/test/java/uk/gov/pay/directdebit/common/exception/ExceptionSummariserTest.java

When there’s a `GoCardlessException` while validating bank account details, don’t log two lines, one with the `GoCardlessException` message immediately, and one without the message when the resultant `InternalServerErrorException`. Instead do all the logging when mapping the `InternalServerErrorException` and enhance this so it always includes the names of and messages from the wrapped exceptions.
We can replace this with something even better when we have structured logging in place.

Tweak logging for errors validating bank details with GoCardless

---

pom.xml
src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/java/uk/gov/pay/directdebit/payments/services/PaymentService.java
src/main/resources/config/config.yaml

- Make DD Connector use JSON logging as the format for outputting log
lines.
- Edits the yaml file to facilitate this by adding ```type: logstash-console```

PP-5511 Add JSON Formatting To DDConnector Logs

---

pom.xml
src/test/java/uk/gov/pay/directdebit/pact/ContractTestSuite.java
src/test/java/uk/gov/pay/directdebit/pact/SelfServiceContractTest.java

Currently when a consumer build is kicked off, the provider contract test will
run in its entirety. For example, in a selfservice build, the dd-connector provider
contract tests will run as well. However, what is run is:
publicapi->dd-connector
selfservice->dd-connector
We really only want to run selfservice->dd-connector in this case.
This commit will allow a dynamic creation of the test suite to run based on a
CONSUMER system property. This will mean shorter run times when a provider
contract test is run as part of a specific consumer build.
* …

PP-5670: Specify the consumer when running contract test

---

src/test/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFacadeTest.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDaoIT.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/resources/GatewayAccountResourceIT.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/services/GatewayAccountServiceTest.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/dao/MandateSearchDaoIT.java
src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/dao/PaymentDaoIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentSearchResourceIT.java
src/test/java/uk/gov/pay/directdebit/payments/services/GovUkPayEventServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/PaymentServiceTest.java
src/test/java/uk/gov/pay/directdebit/payments/services/gocardless/GoCardlessPaymentStateCalculatorTest.java
src/test/java/uk/gov/pay/directdebit/webhook/gocardless/api/GoCardlessWebhookParserTest.java

- Specify a locale when using String.toLowerCase() or toUpperCase().
- Remove "Unnecessary use of fully qualified name" when there is an existing
static import.
I ran PMD linter which uses the `rules.xml` and fixed some things.

BAU Codacy Clean Ups

---

pom.xml
src/main/java/uk/gov/pay/directdebit/DirectDebitConnectorApp.java
src/main/resources/config/config.yaml
src/test/resources/config/test-it-config.yaml

We can remove the timestamp format as the LogstashConsoleAppenderFactory in
pay-java-commons logs the ISO-8601 formatted timestamp by default.
Example log produced by this configuration:
```
{
"@timestamp": "2019-10-16T11:07:13.070+01:00",
"@version": "1",
"message": "Registering jersey handler with root path prefix: /",
"logger_name": "io.dropwizard.server.DefaultServerFactory",
"thread_name": "main",
"level": "INFO",
"level_value": 20000,
"label": "directdebit-connector"
}
```
From local testing I've also verified MDC values are logged and structured
argument values in log lines are logged as a key value pair in the json log.
For example,
```
log.info("This is a log line", StructuredArguments.kv("gateway_account_id","abc"))
```
will produce
```
{
"@timestamp": …
```

PP-5735: Update json logging configuration

---

src/main/resources/config/config.yaml

The application will not start if the SENTRY_DSN is not a well formatted
DSN. This adds a default to avoid problems and to make it simplier to
run locally.
Tested different scenarios for when the `SENTRY_DSN` is set, not set or set to invalid formats. See https://payments-platform.atlassian.net/secure/RapidBoard.jspa?rapidView=59&modal=detail&selectedIssue=PP-5725. The conclusion was to add a default value.

PP-5725 Add default Sentry DSN

---

src/main/java/uk/gov/pay/directdebit/filters/LoggingMDCResponseFilter.java

We shouldn't use MDC.clear as LoggingMDCResponseFilter happens before the
LoggingFilter
(https://github.com/alphagov/pay-java-commons/blob/master/logging/src/main/java/uk/gov/pay/logging/LoggingFilter.java)
is called. This would remove the x_request_id needed in the LoggingFilter.

PP-5893: Manually clear keys

---

pom.xml
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/api/CreateGatewayAccountRequestTest.java
src/test/java/uk/gov/pay/directdebit/gatewayaccounts/dao/GatewayAccountDaoIT.java
src/test/java/uk/gov/pay/directdebit/junit/DropwizardJUnitRunner.java
src/test/java/uk/gov/pay/directdebit/junit/DropwizardTestApplications.java

- Upgrades dropwizard to v2.0.0
- Added `dropwizard-dependencies` as parent as v2.0.0 upgrade doesn't specify transitive dependency versions anymore https://www.dropwizard.io/en/release-2.0.x/manual/upgrade-notes/upgrade-notes-2_0_x.html
We can also include BOM for transitive dependency versions but versions can't be overridden and we may end up with multiple revisions of same library. For example, `jackson-version` current used is `2.10.0` but dropwizard uses `2.10.1`
- Upgraded dropwizard-sentry library to latest version as container might fail to start with error `java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList org.dhatim.dropwizard.sentry.logging.SentryAppenderFactory.getFilterFactories()

PP-6001 Upgrade dropwizard

---

Dockerfile

Updated the the root CA certificate in the container build in preparation for updating the certs installed on the RDS instances.
The combined cert bundle URL does not need to be updated as the URL has not changed, but the updated bundle will be downloaded at build time.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
- Rebuild containers and deploy to test environment
- Ensure app works with **NEW** CA root cert but **OLD** RDS certs. The new ca certs must be backward compatible.
- Schedule the cert update on the RDS instance.

PP-5920: Update RDS root ca cert to 2019

---

dev.yml
manifest.yml

Adds a java buildpack manifest.
To test e.g.
```
cf push --vars-file dev.yml \
--var space=dev-dan \
--var directdebit_connector_route=directdebit-connector-dev-dan.apps.internal \
--var frontend_url=pay-card-frontend-dev-dan.london.cloudapps.digital \
--var adminusers_url=adminusers-dev-dan.apps.internal
```

PP-6029 Add Buildpack manifest

---

manifest.yml

We are using card_frontend_url and directdebit_frontend_url to
distinguish between the frontends.
Checked on test-12 that this var is for dd-frontend...

PP-6031 Correct manifest var for dd-frontend

---

manifest.yml

Adds a missing service binding to manifest.yml ensuring the dd-connector app is bound to the "secrets" user-provided service.

PP-6146: Bind paas app to secret service

---

src/test/java/uk/gov/pay/directdebit/pact/PublicApiContractTest.java
src/test/java/uk/gov/pay/directdebit/pact/SelfServiceContractTest.java

Allow passing in `PACT_BROKER_HOST`, default to existing value. This is
necessary because we're using a different pact broker for concourse ci.
Similar to https://github.com/alphagov/pay-connector/pull/2376/commits/c8550f09611f20a10eda58c21c4843fc106edb90

PP-6445 Make pact broker host configurable

---

pom.xml
src/test/java/uk/gov/pay/directdebit/payments/resources/PaymentSearchResourceIT.java

- The pom references the dropwizard-dependencies as a parent which includes an execution rule for maven-dependency plugin:analyze-only setting the failOnWarning to true (the default is false). This plugin is run as part of the verify phase. We have undeclared transitive dependencies so the analyze-only goal fails and consequently the build.

BAU fix maven dependency plugin

---

.secrets.baseline
Dockerfile

Description:
- This PR updates the AdoptOpenJDK image to 11.0.9
- From https://hub.docker.com/layers/adoptopenjdk/openjdk11/jre-11.0.9_11.1-alpine/images/sha256-58254737530df7f7e7acfe3e7538a027f898ac05accd2e15adcef34d5a33ae72?context=explore

PP-7283 - Update docker image to 11.0.9

---

.github/dependabot.yml

- remove label from dependabot labels. since we no longer merge dependabot PRs for dd apps, we don't want them to appear on the list either.

BAU remove govuk pay label

---

src/main/java/uk/gov/pay/directdebit/webhook/gocardless/support/GoCardlessWebhookVerifier.java

- StringUtils.equals() doesn't implement a constant-time algorithm for comparing inputs. As a result, an attacker may be able to run a timing attack that can forge a valid Webhook signature for an arbitrary body.

PP-8394 fix webhook vulnerability
